export type EmojiCategory =
  | "表情"
  | "手势"
  | "人物"
  | "动物"
  | "自然"
  | "食物"
  | "出行"
  | "活动"
  | "物体"
  | "符号";

export interface EmojiItem {
  emoji: string;
  // 不带冒号的短代码，如 "smile" 对应 ":smile:"
  shortcode: string;
  name: string;
  category: EmojiCategory;
  keywords: string[];
  // 常用项在空查询时优先展示
  popular?: boolean;
}

export const emojiCategories: EmojiCategory[] = [
  "表情",
  "手势",
  "人物",
  "动物",
  "自然",
  "食物",
  "出行",
  "活动",
  "物体",
  "符号",
];

export const emojis: EmojiItem[] = [
  // ===== 表情 =====
  { emoji: "😀", shortcode: "grinning", name: "咧嘴笑", category: "表情", keywords: ["开心", "大笑", "grin", "happy"], popular: true },
  { emoji: "😃", shortcode: "smiley", name: "微笑", category: "表情", keywords: ["开心", "smile", "happy"], popular: true },
  { emoji: "😄", shortcode: "smile", name: "微笑", category: "表情", keywords: ["开心", "smile", "happy"], popular: true },
  { emoji: "😁", shortcode: "grin", name: "露齿笑", category: "表情", keywords: ["开心", "grin"], popular: true },
  { emoji: "😆", shortcode: "laughing", name: "大笑", category: "表情", keywords: ["哈哈", "laugh", "satisfied"], popular: true },
  { emoji: "😅", shortcode: "sweat_smile", name: "尴尬笑", category: "表情", keywords: ["汗", "sweat", "nervous"], popular: true },
  { emoji: "🤣", shortcode: "rofl", name: "笑哭", category: "表情", keywords: ["笑死", "哈哈哈", "rolling", "laughing"], popular: true },
  { emoji: "😂", shortcode: "joy", name: "喜极而泣", category: "表情", keywords: ["笑哭", "笑", "tears", "laugh"], popular: true },
  { emoji: "🙂", shortcode: "slight_smile", name: "微笑", category: "表情", keywords: ["微笑", "smile"], popular: true },
  { emoji: "🙃", shortcode: "upside_down_face", name: "倒脸", category: "表情", keywords: ["颠倒", "玩笑", "upside", "down"] },
  { emoji: "😉", shortcode: "wink", name: "眨眼", category: "表情", keywords: ["俏皮", "wink"], popular: true },
  { emoji: "😊", shortcode: "blush", name: "害羞", category: "表情", keywords: ["脸红", "微笑", "shy", "smile"], popular: true },
  { emoji: "😇", shortcode: "innocent", name: "天使", category: "表情", keywords: ["无辜", "天使", "angel", "holy"] },
  { emoji: "🥰", shortcode: "smiling_face_with_hearts", name: "爱心眼", category: "表情", keywords: ["喜欢", "爱", "hearts", "love"], popular: true },
  { emoji: "😍", shortcode: "heart_eyes", name: "花痴", category: "表情", keywords: ["爱心", "喜欢", "heart", "eyes", "love"], popular: true },
  { emoji: "🤩", shortcode: "star_struck", name: "星星眼", category: "表情", keywords: ["崇拜", "star", "eyes"] },
  { emoji: "😘", shortcode: "kissing_heart", name: "飞吻", category: "表情", keywords: ["亲亲", "kiss", "love"], popular: true },
  { emoji: "😗", shortcode: "kissing", name: "亲吻", category: "表情", keywords: ["kiss"] },
  { emoji: "😋", shortcode: "yum", name: "美味", category: "表情", keywords: ["好吃", "馋", "yummy", "delicious"] },
  { emoji: "😜", shortcode: "stuck_out_tongue_winking_eye", name: "调皮", category: "表情", keywords: ["吐舌", "眨眼", "tongue", "wink"] },
  { emoji: "🤪", shortcode: "zany_face", name: "搞怪", category: "表情", keywords: ["疯狂", "crazy", "zany"] },
  { emoji: "😝", shortcode: "stuck_out_tongue_closed_eyes", name: "吐舌", category: "表情", keywords: ["调皮", "tongue", "eyes"] },
  { emoji: "🤑", shortcode: "money_mouth_face", name: "贪财", category: "表情", keywords: ["钱", "money", "rich"] },
  { emoji: "🤗", shortcode: "hugs", name: "拥抱", category: "表情", keywords: ["抱抱", "hug", "open", "hands"] },
  { emoji: "🤭", shortcode: "hand_over_mouth", name: "捂嘴", category: "表情", keywords: ["惊讶", "偷笑", "giggle", "shh"] },
  { emoji: "🤫", shortcode: "shushing_face", name: "嘘", category: "表情", keywords: ["安静", "小声", "shh", "quiet"] },
  { emoji: "🤔", shortcode: "thinking", name: "思考", category: "表情", keywords: ["想", "疑问", "think", "ponder"], popular: true },
  { emoji: "🤐", shortcode: "zipper_mouth_face", name: "闭嘴", category: "表情", keywords: ["保密", "zipper", "mouth"] },
  { emoji: "🤨", shortcode: "raised_eyebrow", name: "挑眉", category: "表情", keywords: ["怀疑", "skeptical", "eyebrow"] },
  { emoji: "😐", shortcode: "neutral_face", name: "面无表情", category: "表情", keywords: ["冷淡", "neutral", "meh"] },
  { emoji: "😑", shortcode: "expressionless", name: "无语", category: "表情", keywords: ["无表情", "expressionless", "deadpan"] },
  { emoji: "😶", shortcode: "no_mouth", name: "沉默", category: "表情", keywords: ["无嘴", "silent", "mouth"] },
  { emoji: "😏", shortcode: "smirk", name: "得意", category: "表情", keywords: ["坏笑", "smirk", "smug"] },
  { emoji: "😒", shortcode: "unamused", name: "不满", category: "表情", keywords: ["无聊", "呵呵", "unamused", "meh"] },
  { emoji: "🙄", shortcode: "rolling_eyes", name: "翻白眼", category: "表情", keywords: ["无语", "白眼", "roll", "eyes"] },
  { emoji: "😬", shortcode: "grimacing", name: "尴尬", category: "表情", keywords: ["咧嘴", "grimace", "awkward"] },
  { emoji: "🤥", shortcode: "lying_face", name: "说谎", category: "表情", keywords: ["长鼻子", "lie", "liar", "nose"] },
  { emoji: "😌", shortcode: "relieved", name: "放松", category: "表情", keywords: ["安心", "relieved", "relax"] },
  { emoji: "😔", shortcode: "pensive", name: "沉思", category: "表情", keywords: ["难过", "pensive", "sad"] },
  { emoji: "😪", shortcode: "sleepy", name: "困", category: "表情", keywords: ["困倦", "sleepy", "tired"] },
  { emoji: "🤤", shortcode: "drooling_face", name: "流口水", category: "表情", keywords: ["馋", "drool", "hungry"] },
  { emoji: "😴", shortcode: "sleeping", name: "睡觉", category: "表情", keywords: ["睡着", "sleep", "zzz"], popular: true },
  { emoji: "😷", shortcode: "mask", name: "口罩", category: "表情", keywords: ["生病", "感冒", "mask", "sick"] },
  { emoji: "🤒", shortcode: "face_with_thermometer", name: "发烧", category: "表情", keywords: ["生病", "thermometer", "sick"] },
  { emoji: "🤕", shortcode: "face_with_head_bandage", name: "受伤", category: "表情", keywords: ["头绑带", "hurt", "bandage"] },
  { emoji: "🤢", shortcode: "nauseated_face", name: "恶心", category: "表情", keywords: ["想吐", "sick", "nausea"] },
  { emoji: "🤮", shortcode: "vomiting_face", name: "呕吐", category: "表情", keywords: ["吐了", "vomit", "sick"] },
  { emoji: "🤧", shortcode: "sneezing_face", name: "打喷嚏", category: "表情", keywords: ["感冒", "sneeze", "achoo"] },
  { emoji: "🥵", shortcode: "hot_face", name: "热", category: "表情", keywords: ["酷热", "hot", "sweating"] },
  { emoji: "🥶", shortcode: "cold_face", name: "冷", category: "表情", keywords: ["寒冷", "cold", "freezing"] },
  { emoji: "🥴", shortcode: "woozy_face", name: "头晕", category: "表情", keywords: ["晕", "woozy", "dizzy"] },
  { emoji: "😵", shortcode: "dizzy_face", name: "眩晕", category: "表情", keywords: ["晕", "dizzy", "crossed"] },
  { emoji: "🤯", shortcode: "exploding_head", name: "震惊", category: "表情", keywords: ["爆炸头", "mind", "blown"] },
  { emoji: "🤠", shortcode: "cowboy_hat_face", name: "牛仔", category: "表情", keywords: ["帽子", "cowboy", "hat"] },
  { emoji: "🥳", shortcode: "partying_face", name: "庆祝", category: "表情", keywords: ["派对", "party", "celebration", "congrats"], popular: true },
  { emoji: "🥸", shortcode: "disguised_face", name: "伪装", category: "表情", keywords: ["假胡子", "disguise", "incognito"] },
  { emoji: "😎", shortcode: "sunglasses", name: "墨镜", category: "表情", keywords: ["酷", "cool", "sunglasses"], popular: true },
  { emoji: "🤓", shortcode: "nerd_face", name: "书呆子", category: "表情", keywords: ["眼镜", "nerd", "geek"] },
  { emoji: "🧐", shortcode: "monocle", name: "单片眼镜", category: "表情", keywords: ["考究", "monocle", "classy"] },
  { emoji: "😕", shortcode: "confused", name: "困惑", category: "表情", keywords: ["疑问", "confused", "puzzled"] },
  { emoji: "😟", shortcode: "worried", name: "担心", category: "表情", keywords: ["忧虑", "worried", "concerned"] },
  { emoji: "🙁", shortcode: "slightly_frowning_face", name: "沮丧", category: "表情", keywords: ["难过", "frown", "sad"] },
  { emoji: "😮", shortcode: "surprised", name: "惊讶", category: "表情", keywords: ["哇", "surprised", "wow"] },
  { emoji: "😯", shortcode: "hushed", name: "吃惊", category: "表情", keywords: ["安静", "hushed", "shocked"] },
  { emoji: "😲", shortcode: "astonished", name: "目瞪口呆", category: "表情", keywords: ["震惊", "astonished", "amazed"] },
  { emoji: "😳", shortcode: "flushed", name: "脸红", category: "表情", keywords: ["害羞", "flushed", "embarrassed"] },
  { emoji: "🥺", shortcode: "pleading_face", name: "恳求", category: "表情", keywords: ["可怜", "pleading", "puppy", "beg"], popular: true },
  { emoji: "😦", shortcode: "frowning_face_with_open_mouth", name: "难过", category: "表情", keywords: ["惊讶", "frowning", "open"] },
  { emoji: "😧", shortcode: "anguished", name: "痛苦", category: "表情", keywords: ["焦虑", "anguished", "pained"] },
  { emoji: "😨", shortcode: "fearful", name: "害怕", category: "表情", keywords: ["恐惧", "fearful", "scared"] },
  { emoji: "😰", shortcode: "anxious_face_with_sweat", name: "焦虑", category: "表情", keywords: ["紧张", "anxious", "sweat"] },
  { emoji: "😥", shortcode: "sad_but_relieved_face", name: "松口气", category: "表情", keywords: ["遗憾", "relieved", "sad"] },
  { emoji: "😢", shortcode: "crying_face", name: "哭泣", category: "表情", keywords: ["哭", "眼泪", "cry", "tear"], popular: true },
  { emoji: "😭", shortcode: "loudly_crying_face", name: "大哭", category: "表情", keywords: ["哭", "sobbing", "cry"], popular: true },
  { emoji: "😱", shortcode: "scream", name: "尖叫", category: "表情", keywords: ["惊恐", "scream", "shock"] },
  { emoji: "😖", shortcode: "confounded_face", name: "抓狂", category: "表情", keywords: ["烦躁", "confounded", "distressed"] },
  { emoji: "😣", shortcode: "persevering_face", name: "忍耐", category: "表情", keywords: ["坚持", "persevere", "struggle"] },
  { emoji: "😞", shortcode: "disappointed", name: "失望", category: "表情", keywords: ["伤心", "disappointed", "sad"] },
  { emoji: "😓", shortcode: "downcast_face_with_sweat", name: "冒汗", category: "表情", keywords: ["尴尬", "sweat", "downcast"] },
  { emoji: "😩", shortcode: "weary", name: "疲惫", category: "表情", keywords: ["累", "weary", "tired"] },
  { emoji: "😫", shortcode: "tired_face", name: "累了", category: "表情", keywords: ["困", "tired", "exhausted"] },
  { emoji: "🥱", shortcode: "yawning_face", name: "打哈欠", category: "表情", keywords: ["困", "yawning", "tired"] },
  { emoji: "😤", shortcode: "triumph", name: "哼", category: "表情", keywords: ["生气", "triumph", "steam", "angry"] },
  { emoji: "😡", shortcode: "pouting_face", name: "愤怒", category: "表情", keywords: ["生气", "angry", "rage"], popular: true },
  { emoji: "😠", shortcode: "angry", name: "生气", category: "表情", keywords: ["愤怒", "angry", "mad"] },
  { emoji: "🤬", shortcode: "symbols_over_mouth", name: "骂人", category: "表情", keywords: ["脏话", "cursing", "symbols"] },
  { emoji: "😈", shortcode: "smiling_imp", name: "小恶魔", category: "表情", keywords: ["坏笑", "devil", "imp"] },
  { emoji: "👿", shortcode: "imp", name: "恶魔", category: "表情", keywords: ["生气", "devil", "imp"] },
  { emoji: "💀", shortcode: "skull", name: "骷髅", category: "表情", keywords: ["死亡", "skull", "dead"] },
  { emoji: "☠️", shortcode: "skull_and_crossbones", name: "骷髅头", category: "表情", keywords: ["危险", "poison", "skull"] },
  { emoji: "💩", shortcode: "poop", name: "便便", category: "表情", keywords: ["屎", "poop", "shit", "hankey"] },
  { emoji: "🤡", shortcode: "clown_face", name: "小丑", category: "表情", keywords: ["clown", "jester"] },
  { emoji: "👹", shortcode: "ogre", name: "妖怪", category: "表情", keywords: ["鬼", "ogre", "oni"] },
  { emoji: "👺", shortcode: "goblin", name: "天狗", category: "表情", keywords: ["鬼", "goblin", "tengu"] },
  { emoji: "👻", shortcode: "ghost", name: "幽灵", category: "表情", keywords: ["鬼", "ghost", "spooky"], popular: true },
  { emoji: "👽", shortcode: "alien", name: "外星人", category: "表情", keywords: ["alien", "ufo", "space"] },
  { emoji: "👾", shortcode: "alien_monster", name: "外星怪物", category: "表情", keywords: ["游戏", "alien", "monster"] },
  { emoji: "🤖", shortcode: "robot", name: "机器人", category: "表情", keywords: ["robot", "android"], popular: true },
  { emoji: "😺", shortcode: "smiley_cat", name: "开心猫", category: "表情", keywords: ["猫", "cat", "happy"] },
  { emoji: "😸", shortcode: "smile_cat", name: "微笑猫", category: "表情", keywords: ["猫", "cat", "smile"] },
  { emoji: "😹", shortcode: "joy_cat", name: "笑哭猫", category: "表情", keywords: ["猫", "cat", "joy"] },
  { emoji: "😻", shortcode: "heart_eyes_cat", name: "花痴猫", category: "表情", keywords: ["猫", "cat", "love"] },
  { emoji: "😼", shortcode: "smirk_cat", name: "得意猫", category: "表情", keywords: ["猫", "cat", "smirk"] },
  { emoji: "😽", shortcode: "kissing_cat", name: "亲亲猫", category: "表情", keywords: ["猫", "cat", "kiss"] },
  { emoji: "🙀", shortcode: "weary_cat", name: "惊吓猫", category: "表情", keywords: ["猫", "cat", "weary"] },
  { emoji: "😿", shortcode: "crying_cat", name: "哭泣猫", category: "表情", keywords: ["猫", "cat", "cry"] },
  { emoji: "😾", shortcode: "pouting_cat", name: "生气猫", category: "表情", keywords: ["猫", "cat", "pout"] },
  { emoji: "🙈", shortcode: "see_no_evil", name: "捂眼", category: "表情", keywords: ["不看", "monkey", "evil"] },
  { emoji: "🙉", shortcode: "hear_no_evil", name: "捂耳", category: "表情", keywords: ["不听", "monkey", "evil"] },
  { emoji: "🙊", shortcode: "speak_no_evil", name: "捂嘴", category: "表情", keywords: ["不说", "monkey", "evil"] },
  { emoji: "💋", shortcode: "kiss", name: "唇印", category: "表情", keywords: ["亲亲", "kiss", "lips"] },
  { emoji: "💌", shortcode: "love_letter", name: "情书", category: "表情", keywords: ["信", "love", "letter"] },
  { emoji: "💘", shortcode: "cupid", name: "丘比特", category: "表情", keywords: ["爱", "cupid", "arrow", "love"] },
  { emoji: "💝", shortcode: "gift_heart", name: "礼物心", category: "表情", keywords: ["礼物", "gift", "heart", "love"] },
  { emoji: "💖", shortcode: "sparkling_heart", name: "闪心", category: "表情", keywords: ["爱", "sparkle", "heart"] },
  { emoji: "💗", shortcode: "growing_heart", name: "心跳", category: "表情", keywords: ["爱", "growing", "heart"] },
  { emoji: "💓", shortcode: "beating_heart", name: "心动", category: "表情", keywords: ["爱", "beating", "heart"] },
  { emoji: "💞", shortcode: "revolving_hearts", name: "旋转心", category: "表情", keywords: ["爱", "revolving", "heart"] },
  { emoji: "💕", shortcode: "two_hearts", name: "双心", category: "表情", keywords: ["爱", "two", "hearts"] },
  { emoji: "💟", shortcode: "heart_decoration", name: "心形", category: "表情", keywords: ["爱", "heart", "decoration"] },
  { emoji: "❣️", shortcode: "heart_exclamation", name: "感叹心", category: "表情", keywords: ["爱", "heart", "exclamation"] },
  { emoji: "💔", shortcode: "broken_heart", name: "心碎", category: "表情", keywords: ["伤心", "broken", "heart"], popular: true },
  { emoji: "❤️", shortcode: "heart", name: "红心", category: "表情", keywords: ["爱心", "love", "heart"], popular: true },
  { emoji: "🧡", shortcode: "orange_heart", name: "橙心", category: "表情", keywords: ["爱", "orange", "heart"] },
  { emoji: "💛", shortcode: "yellow_heart", name: "黄心", category: "表情", keywords: ["爱", "yellow", "heart"] },
  { emoji: "💚", shortcode: "green_heart", name: "绿心", category: "表情", keywords: ["爱", "green", "heart"] },
  { emoji: "💙", shortcode: "blue_heart", name: "蓝心", category: "表情", keywords: ["爱", "blue", "heart"] },
  { emoji: "💜", shortcode: "purple_heart", name: "紫心", category: "表情", keywords: ["爱", "purple", "heart"] },
  { emoji: "🤎", shortcode: "brown_heart", name: "棕心", category: "表情", keywords: ["爱", "brown", "heart"] },
  { emoji: "🖤", shortcode: "black_heart", name: "黑心", category: "表情", keywords: ["爱", "black", "heart"] },
  { emoji: "🤍", shortcode: "white_heart", name: "白心", category: "表情", keywords: ["爱", "white", "heart"] },
  { emoji: "💯", shortcode: "hundred_points", name: "满分", category: "表情", keywords: ["100", "一百", "perfect", "hundred"] },
  { emoji: "💢", shortcode: "anger", name: "生气符号", category: "表情", keywords: ["愤怒", "anger", "angry"] },
  { emoji: "💥", shortcode: "boom", name: "爆炸", category: "表情", keywords: ["碰撞", "boom", "collision"] },
  { emoji: "💫", shortcode: "dizzy", name: "眩晕星", category: "表情", keywords: ["晕", "star", "dizzy"] },
  { emoji: "💦", shortcode: "sweat_drops", name: "汗滴", category: "表情", keywords: ["汗水", "sweat", "drops"] },
  { emoji: "💨", shortcode: "dash", name: "疾风", category: "表情", keywords: ["跑", "风", "dash", "wind"] },
  { emoji: "🕳️", shortcode: "hole", name: "洞", category: "表情", keywords: ["黑洞", "hole"] },
  { emoji: "💣", shortcode: "bomb", name: "炸弹", category: "表情", keywords: ["bomb", "boom"] },
  { emoji: "💬", shortcode: "speech_balloon", name: "对话气泡", category: "表情", keywords: ["说话", "speech", "balloon", "chat"] },
  { emoji: "🗨️", shortcode: "left_speech_bubble", name: "对话泡泡", category: "表情", keywords: ["说话", "speech", "bubble"] },
  { emoji: "🗯️", shortcode: "right_anger_bubble", name: "愤怒气泡", category: "表情", keywords: ["生气", "anger", "bubble"] },
  { emoji: "💭", shortcode: "thought_balloon", name: "想法气泡", category: "表情", keywords: ["思考", "thought", "balloon"] },
  { emoji: "💤", shortcode: "zzz", name: "睡觉符号", category: "表情", keywords: ["睡觉", "困", "sleep", "zzz"] },

  // ===== 手势 =====
  { emoji: "👋", shortcode: "wave", name: "挥手", category: "手势", keywords: ["再见", "你好", "wave", "hi", "bye"], popular: true },
  { emoji: "🤚", shortcode: "raised_back_of_hand", name: "手背", category: "手势", keywords: ["举手", "hand"] },
  { emoji: "🖐️", shortcode: "hand", name: "手掌", category: "手势", keywords: ["手", "open", "hand"] },
  { emoji: "✋", shortcode: "raised_hand", name: "举手", category: "手势", keywords: ["手", "raised", "hand"] },
  { emoji: "🖖", shortcode: "vulcan_salute", name: "瓦肯举手礼", category: "手势", keywords: ["spock", "vulcan", "salute"] },
  { emoji: "👌", shortcode: "ok_hand", name: "OK", category: "手势", keywords: ["好", "可以", "ok", "perfect"], popular: true },
  { emoji: "🤌", shortcode: "pinched_fingers", name: "捏指", category: "手势", keywords: ["质疑", "pinched", "fingers"] },
  { emoji: "🤏", shortcode: "pinching_hand", name: "捏", category: "手势", keywords: ["一点", "pinching", "tiny"] },
  { emoji: "✌️", shortcode: "victory", name: "胜利", category: "手势", keywords: ["剪刀手", "victory", "peace", "v"], popular: true },
  { emoji: "🤞", shortcode: "crossed_fingers", name: "好运", category: "手势", keywords: ["祈祷", "crossed", "fingers", "luck"] },
  { emoji: "🤟", shortcode: "love_you_gesture", name: "爱你", category: "手势", keywords: ["摇滚", "love", "you", "gesture"] },
  { emoji: "🤘", shortcode: "metal", name: "摇滚", category: "手势", keywords: ["金属", "rock", "metal", "horns"] },
  { emoji: "🤙", shortcode: "call_me_hand", name: "打电话", category: "手势", keywords: ["联系", "call", "me", "shaka"] },
  { emoji: "👈", shortcode: "point_left", name: "指向左", category: "手势", keywords: ["左边", "point", "left"] },
  { emoji: "👉", shortcode: "point_right", name: "指向右", category: "手势", keywords: ["右边", "point", "right"] },
  { emoji: "👆", shortcode: "point_up_2", name: "指向上", category: "手势", keywords: ["上面", "point", "up"] },
  { emoji: "👇", shortcode: "point_down", name: "指向下", category: "手势", keywords: ["下面", "point", "down"] },
  { emoji: "☝️", shortcode: "point_up", name: "食指向上", category: "手势", keywords: ["point", "up"] },
  { emoji: "👍", shortcode: "thumbsup", name: "点赞", category: "手势", keywords: ["赞", "好", "thumbs", "up", "like"], popular: true },
  { emoji: "👎", shortcode: "thumbsdown", name: "点踩", category: "手势", keywords: ["差", "thumbs", "down", "dislike"], popular: true },
  { emoji: "✊", shortcode: "fist", name: "拳头", category: "手势", keywords: ["加油", "fist", "punch"] },
  { emoji: "👊", shortcode: "punch", name: "出拳", category: "手势", keywords: ["拳头", "fist", "punch", "oncoming"] },
  { emoji: "🤛", shortcode: "left_facing_fist", name: "左拳", category: "手势", keywords: ["fist", "left"] },
  { emoji: "🤜", shortcode: "right_facing_fist", name: "右拳", category: "手势", keywords: ["fist", "right"] },
  { emoji: "👏", shortcode: "clap", name: "鼓掌", category: "手势", keywords: ["鼓掌", "clap", "applause"], popular: true },
  { emoji: "🙌", shortcode: "raised_hands", name: "举起双手", category: "手势", keywords: ["庆祝", "欢呼", "raised", "hands"], popular: true },
  { emoji: "👐", shortcode: "open_hands", name: "张开手", category: "手势", keywords: ["open", "hands"] },
  { emoji: "🤲", shortcode: "palms_up_together", name: "捧手", category: "手势", keywords: ["祈祷", "palms", "up"] },
  { emoji: "🤝", shortcode: "handshake", name: "握手", category: "手势", keywords: ["合作", "handshake", "deal"], popular: true },
  { emoji: "🙏", shortcode: "pray", name: "双手合十", category: "手势", keywords: ["祈祷", "谢谢", "拜托", "pray", "thanks", "please"], popular: true },
  { emoji: "✍️", shortcode: "writing_hand", name: "写字", category: "手势", keywords: ["写作", "writing", "hand"] },
  { emoji: "💪", shortcode: "muscle", name: "肌肉", category: "手势", keywords: ["力量", "加油", "muscle", "strong"], popular: true },
  { emoji: "🦾", shortcode: "mechanical_arm", name: "机械臂", category: "手势", keywords: ["机器人", "mechanical", "arm"] },
  { emoji: "🦿", shortcode: "mechanical_leg", name: "机械腿", category: "手势", keywords: ["机器人", "mechanical", "leg"] },
  { emoji: "🦵", shortcode: "leg", name: "腿", category: "手势", keywords: ["腿", "leg"] },
  { emoji: "🦶", shortcode: "foot", name: "脚", category: "手势", keywords: ["脚", "foot"] },
  { emoji: "👂", shortcode: "ear", name: "耳朵", category: "手势", keywords: ["听", "ear"] },
  { emoji: "👃", shortcode: "nose", name: "鼻子", category: "手势", keywords: ["nose"] },
  { emoji: "🧠", shortcode: "brain", name: "大脑", category: "手势", keywords: ["脑", "brain", "mind"] },
  { emoji: "🫀", shortcode: "anatomical_heart", name: "心脏", category: "手势", keywords: ["heart", "anatomical"] },
  { emoji: "🫁", shortcode: "lungs", name: "肺", category: "手势", keywords: ["lungs"] },
  { emoji: "🦷", shortcode: "tooth", name: "牙齿", category: "手势", keywords: ["牙", "tooth"] },
  { emoji: "👅", shortcode: "tongue", name: "舌头", category: "手势", keywords: ["舔", "tongue"] },
  { emoji: "👄", shortcode: "lips", name: "嘴唇", category: "手势", keywords: ["嘴", "lips", "mouth"] },
  { emoji: "👁️", shortcode: "eye", name: "眼睛", category: "手势", keywords: ["眼", "eye"] },
  { emoji: "👀", shortcode: "eyes", name: "双眼", category: "手势", keywords: ["看", "eyes"], popular: true },

  // ===== 人物 =====
  { emoji: "👶", shortcode: "baby", name: "婴儿", category: "人物", keywords: ["宝宝", "baby", "newborn"] },
  { emoji: "🧒", shortcode: "child", name: "儿童", category: "人物", keywords: ["小孩", "child"] },
  { emoji: "👦", shortcode: "boy", name: "男孩", category: "人物", keywords: ["boy"] },
  { emoji: "👧", shortcode: "girl", name: "女孩", category: "人物", keywords: ["girl"] },
  { emoji: "🧑", shortcode: "person", name: "人", category: "人物", keywords: ["person", "adult"] },
  { emoji: "👱", shortcode: "person_blond_hair", name: "金发人", category: "人物", keywords: ["金发", "blond", "person"] },
  { emoji: "👨", shortcode: "man", name: "男人", category: "人物", keywords: ["man"], popular: true },
  { emoji: "🧔", shortcode: "bearded_person", name: "胡子", category: "人物", keywords: ["beard", "man"] },
  { emoji: "👩", shortcode: "woman", name: "女人", category: "人物", keywords: ["woman"], popular: true },
  { emoji: "🧓", shortcode: "older_person", name: "老人", category: "人物", keywords: ["老年", "older", "person"] },
  { emoji: "👴", shortcode: "older_man", name: "老爷爷", category: "人物", keywords: ["老人", "old", "man"] },
  { emoji: "👵", shortcode: "older_woman", name: "老奶奶", category: "人物", keywords: ["老人", "old", "woman"] },
  { emoji: "👮", shortcode: "police_officer", name: "警察", category: "人物", keywords: ["police", "cop", "officer"] },
  { emoji: "🕵️", shortcode: "detective", name: "侦探", category: "人物", keywords: ["detective", "spy"] },
  { emoji: "👷", shortcode: "construction_worker", name: "工人", category: "人物", keywords: ["construction", "worker"] },
  { emoji: "💂", shortcode: "guard", name: "卫兵", category: "人物", keywords: ["guard"] },
  { emoji: "👳", shortcode: "person_with_turban", name: "头巾", category: "人物", keywords: ["turban", "person"] },
  { emoji: "🤴", shortcode: "prince", name: "王子", category: "人物", keywords: ["prince"] },
  { emoji: "👸", shortcode: "princess", name: "公主", category: "人物", keywords: ["princess"], popular: true },
  { emoji: "👲", shortcode: "man_with_chinese_cap", name: "瓜皮帽", category: "人物", keywords: ["中国", "chinese", "cap", "man"] },
  { emoji: "🧕", shortcode: "woman_with_headscarf", name: "头巾女", category: "人物", keywords: ["headscarf", "woman"] },
  { emoji: "🤵", shortcode: "man_in_tuxedo", name: "新郎", category: "人物", keywords: ["西装", "tuxedo", "groom"] },
  { emoji: "👰", shortcode: "bride_with_veil", name: "新娘", category: "人物", keywords: ["婚纱", "bride", "veil"] },
  { emoji: "🤰", shortcode: "pregnant_woman", name: "孕妇", category: "人物", keywords: ["pregnant", "woman"] },
  { emoji: "🤱", shortcode: "breast_feeding", name: "哺乳", category: "人物", keywords: ["breast", "feeding"] },
  { emoji: "👼", shortcode: "angel", name: "天使宝宝", category: "人物", keywords: ["天使", "angel", "baby"] },
  { emoji: "🎅", shortcode: "santa", name: "圣诞老人", category: "人物", keywords: ["圣诞", "santa", "claus"], popular: true },
  { emoji: "🤶", shortcode: "mrs_claus", name: "圣诞奶奶", category: "人物", keywords: ["圣诞", "mrs", "claus"] },
  { emoji: "🦸", shortcode: "superhero", name: "超级英雄", category: "人物", keywords: ["superhero", "hero"] },
  { emoji: "🦹", shortcode: "supervillain", name: "超级反派", category: "人物", keywords: ["villain", "supervillain"] },
  { emoji: "🧙", shortcode: "mage", name: "法师", category: "人物", keywords: ["魔法", "mage", "wizard"] },
  { emoji: "🧚", shortcode: "fairy", name: "精灵", category: "人物", keywords: ["仙女", "fairy"] },
  { emoji: "🧛", shortcode: "vampire", name: "吸血鬼", category: "人物", keywords: ["vampire"] },
  { emoji: "🧜", shortcode: "merperson", name: "美人鱼", category: "人物", keywords: ["mermaid", "merperson"] },
  { emoji: "🧝", shortcode: "elf", name: "精灵", category: "人物", keywords: ["elf"] },
  { emoji: "🧞", shortcode: "genie", name: "灯神", category: "人物", keywords: ["genie"] },
  { emoji: "🧟", shortcode: "zombie", name: "僵尸", category: "人物", keywords: ["zombie"] },
  { emoji: "💆", shortcode: "massage", name: "按摩", category: "人物", keywords: ["massage", "spa"] },
  { emoji: "💇", shortcode: "haircut", name: "理发", category: "人物", keywords: ["haircut"] },
  { emoji: "🚶", shortcode: "walking", name: "走路", category: "人物", keywords: ["walking", "walk"] },
  { emoji: "🧍", shortcode: "standing_person", name: "站立", category: "人物", keywords: ["standing"] },
  { emoji: "🧎", shortcode: "kneeling_person", name: "跪", category: "人物", keywords: ["kneeling"] },
  { emoji: "🏃", shortcode: "runner", name: "跑步", category: "人物", keywords: ["跑", "跑步", "running", "runner"] },
  { emoji: "💃", shortcode: "dancer", name: "跳舞", category: "人物", keywords: ["舞蹈", "dancer", "dancing"] },
  { emoji: "🕺", shortcode: "man_dancing", name: "男人跳舞", category: "人物", keywords: ["舞蹈", "man", "dancing"] },
  { emoji: "👯", shortcode: "dancers", name: "双人舞", category: "人物", keywords: ["dancers", "party"] },
  { emoji: "🧖", shortcode: "person_in_steamy_room", name: "蒸桑拿", category: "人物", keywords: ["桑拿", "steamy", "sauna"] },
  { emoji: "🧗", shortcode: "climbing", name: "攀岩", category: "人物", keywords: ["climbing"] },
  { emoji: "🤺", shortcode: "fencer", name: "击剑", category: "人物", keywords: ["fencing", "fencer"] },
  { emoji: "🏇", shortcode: "horse_racing", name: "赛马", category: "人物", keywords: ["horse", "racing"] },
  { emoji: "⛷️", shortcode: "skier", name: "滑雪", category: "人物", keywords: ["skiing", "skier"] },
  { emoji: "🏂", shortcode: "snowboarder", name: "单板滑雪", category: "人物", keywords: ["snowboarder", "snowboard"] },
  { emoji: "🏌️", shortcode: "golfing", name: "高尔夫", category: "人物", keywords: ["golf", "golfing"] },
  { emoji: "🏄", shortcode: "surfer", name: "冲浪", category: "人物", keywords: ["surfing", "surfer"] },
  { emoji: "🚣", shortcode: "rowboat", name: "划船", category: "人物", keywords: ["rowing", "rowboat"] },
  { emoji: "🏊", shortcode: "swimmer", name: "游泳", category: "人物", keywords: ["swimming", "swimmer"] },
  { emoji: "⛹️", shortcode: "basketball_player", name: "打篮球", category: "人物", keywords: ["basketball", "player"] },
  { emoji: "🏋️", shortcode: "weight_lifter", name: "举重", category: "人物", keywords: ["weight", "lifting"] },
  { emoji: "🚴", shortcode: "cyclist", name: "骑车", category: "人物", keywords: ["cycling", "cyclist", "bike"] },
  { emoji: "🚵", shortcode: "mountain_bicyclist", name: "山地车", category: "人物", keywords: ["mountain", "biking"] },
  { emoji: "🤸", shortcode: "cartwheeling", name: "侧手翻", category: "人物", keywords: ["cartwheel", "gymnastics"] },
  { emoji: "🤼", shortcode: "wrestling", name: "摔跤", category: "人物", keywords: ["wrestling"] },
  { emoji: "🤽", shortcode: "water_polo", name: "水球", category: "人物", keywords: ["water", "polo"] },
  { emoji: "🤾", shortcode: "handball", name: "手球", category: "人物", keywords: ["handball"] },
  { emoji: "🤹", shortcode: "juggling", name: "杂耍", category: "人物", keywords: ["juggling"] },
  { emoji: "🧘", shortcode: "person_in_lotus_position", name: "冥想", category: "人物", keywords: ["瑜伽", "meditation", "lotus"] },
  { emoji: "🛀", shortcode: "bath", name: "洗澡", category: "人物", keywords: ["泡澡", "bath"] },
  { emoji: "🛌", shortcode: "sleeping_bed", name: "睡觉", category: "人物", keywords: ["sleeping", "bed"] },

  // ===== 动物 =====
  { emoji: "🐵", shortcode: "monkey_face", name: "猴脸", category: "动物", keywords: ["猴子", "monkey"] },
  { emoji: "🐒", shortcode: "monkey", name: "猴子", category: "动物", keywords: ["monkey"] },
  { emoji: "🦍", shortcode: "gorilla", name: "大猩猩", category: "动物", keywords: ["gorilla"] },
  { emoji: "🦧", shortcode: "orangutan", name: "红毛猩猩", category: "动物", keywords: ["orangutan"] },
  { emoji: "🐶", shortcode: "dog", name: "狗", category: "动物", keywords: ["狗狗", "小狗", "dog", "puppy"], popular: true },
  { emoji: "🐕", shortcode: "dog2", name: "狗", category: "动物", keywords: ["dog"] },
  { emoji: "🦮", shortcode: "guide_dog", name: "导盲犬", category: "动物", keywords: ["guide", "dog"] },
  { emoji: "🐕🦺", shortcode: "service_dog", name: "服务犬", category: "动物", keywords: ["service", "dog"] },
  { emoji: "🐩", shortcode: "poodle", name: "贵宾犬", category: "动物", keywords: ["poodle"] },
  { emoji: "🐺", shortcode: "wolf", name: "狼", category: "动物", keywords: ["wolf"] },
  { emoji: "🦊", shortcode: "fox_face", name: "狐狸", category: "动物", keywords: ["fox"] },
  { emoji: "🐱", shortcode: "cat", name: "猫", category: "动物", keywords: ["猫咪", "小猫", "cat", "kitty"], popular: true },
  { emoji: "🐈", shortcode: "cat2", name: "猫", category: "动物", keywords: ["cat"] },
  { emoji: "🦁", shortcode: "lion", name: "狮子", category: "动物", keywords: ["lion"], popular: true },
  { emoji: "🐯", shortcode: "tiger", name: "老虎", category: "动物", keywords: ["tiger"], popular: true },
  { emoji: "🐅", shortcode: "tiger2", name: "老虎", category: "动物", keywords: ["tiger"] },
  { emoji: "🐆", shortcode: "leopard", name: "豹子", category: "动物", keywords: ["leopard"] },
  { emoji: "🐴", shortcode: "horse", name: "马", category: "动物", keywords: ["horse"], popular: true },
  { emoji: "🦄", shortcode: "unicorn", name: "独角兽", category: "动物", keywords: ["unicorn"], popular: true },
  { emoji: "🦓", shortcode: "zebra", name: "斑马", category: "动物", keywords: ["zebra"] },
  { emoji: "🦌", shortcode: "deer", name: "鹿", category: "动物", keywords: ["deer"] },
  { emoji: "🐮", shortcode: "cow", name: "奶牛", category: "动物", keywords: ["牛", "cow"] },
  { emoji: "🐂", shortcode: "ox", name: "公牛", category: "动物", keywords: ["ox"] },
  { emoji: "🐃", shortcode: "water_buffalo", name: "水牛", category: "动物", keywords: ["buffalo"] },
  { emoji: "🐄", shortcode: "cow2", name: "奶牛", category: "动物", keywords: ["cow"] },
  { emoji: "🐷", shortcode: "pig", name: "猪", category: "动物", keywords: ["pig"], popular: true },
  { emoji: "🐖", shortcode: "pig2", name: "猪", category: "动物", keywords: ["pig"] },
  { emoji: "🐗", shortcode: "boar", name: "野猪", category: "动物", keywords: ["boar"] },
  { emoji: "🐽", shortcode: "pig_nose", name: "猪鼻子", category: "动物", keywords: ["pig", "nose"] },
  { emoji: "🐏", shortcode: "ram", name: "公羊", category: "动物", keywords: ["ram"] },
  { emoji: "🐑", shortcode: "sheep", name: "绵羊", category: "动物", keywords: ["sheep"], popular: true },
  { emoji: "🐐", shortcode: "goat", name: "山羊", category: "动物", keywords: ["goat"] },
  { emoji: "🐪", shortcode: "camel", name: "骆驼", category: "动物", keywords: ["camel"] },
  { emoji: "🐫", shortcode: "two_hump_camel", name: "双峰骆驼", category: "动物", keywords: ["camel"] },
  { emoji: "🦙", shortcode: "llama", name: "羊驼", category: "动物", keywords: ["llama", "alpaca"] },
  { emoji: "🦒", shortcode: "giraffe", name: "长颈鹿", category: "动物", keywords: ["giraffe"] },
  { emoji: "🐘", shortcode: "elephant", name: "大象", category: "动物", keywords: ["elephant"] },
  { emoji: "🦣", shortcode: "mammoth", name: "猛犸象", category: "动物", keywords: ["mammoth"] },
  { emoji: "🦏", shortcode: "rhinoceros", name: "犀牛", category: "动物", keywords: ["rhino", "rhinoceros"] },
  { emoji: "🦛", shortcode: "hippopotamus", name: "河马", category: "动物", keywords: ["hippo"] },
  { emoji: "🐭", shortcode: "mouse", name: "老鼠", category: "动物", keywords: ["mouse"] },
  { emoji: "🐁", shortcode: "mouse2", name: "老鼠", category: "动物", keywords: ["mouse"] },
  { emoji: "🐀", shortcode: "rat", name: "大鼠", category: "动物", keywords: ["rat"] },
  { emoji: "🐹", shortcode: "hamster", name: "仓鼠", category: "动物", keywords: ["hamster"], popular: true },
  { emoji: "🐰", shortcode: "rabbit", name: "兔子", category: "动物", keywords: ["rabbit", "bunny"], popular: true },
  { emoji: "🐇", shortcode: "rabbit2", name: "兔子", category: "动物", keywords: ["rabbit"] },
  { emoji: "🐿️", shortcode: "squirrel", name: "松鼠", category: "动物", keywords: ["squirrel"] },
  { emoji: "🦫", shortcode: "beaver", name: "河狸", category: "动物", keywords: ["beaver"] },
  { emoji: "🦔", shortcode: "hedgehog", name: "刺猬", category: "动物", keywords: ["hedgehog"] },
  { emoji: "🦇", shortcode: "bat", name: "蝙蝠", category: "动物", keywords: ["bat"] },
  { emoji: "🐻", shortcode: "bear", name: "熊", category: "动物", keywords: ["bear"], popular: true },
  { emoji: "🐨", shortcode: "koala", name: "考拉", category: "动物", keywords: ["koala"] },
  { emoji: "🐼", shortcode: "panda_face", name: "熊猫", category: "动物", keywords: ["panda"], popular: true },
  { emoji: "🦥", shortcode: "sloth", name: "树懒", category: "动物", keywords: ["sloth"] },
  { emoji: "🦦", shortcode: "otter", name: "水獭", category: "动物", keywords: ["otter"] },
  { emoji: "🦨", shortcode: "skunk", name: "臭鼬", category: "动物", keywords: ["skunk"] },
  { emoji: "🦘", shortcode: "kangaroo", name: "袋鼠", category: "动物", keywords: ["kangaroo"] },
  { emoji: "🦡", shortcode: "badger", name: "獾", category: "动物", keywords: ["badger"] },
  { emoji: "🐾", shortcode: "paw_prints", name: "爪印", category: "动物", keywords: ["paw", "prints"] },
  { emoji: "🦃", shortcode: "turkey", name: "火鸡", category: "动物", keywords: ["turkey"] },
  { emoji: "🐔", shortcode: "chicken", name: "鸡", category: "动物", keywords: ["chicken"] },
  { emoji: "🐓", shortcode: "rooster", name: "公鸡", category: "动物", keywords: ["rooster"] },
  { emoji: "🐣", shortcode: "hatching_chick", name: "孵蛋小鸡", category: "动物", keywords: ["chick", "hatching"] },
  { emoji: "🐤", shortcode: "baby_chick", name: "小鸡", category: "动物", keywords: ["chick", "baby"] },
  { emoji: "🐥", shortcode: "hatched_chick", name: "出壳小鸡", category: "动物", keywords: ["chick"] },
  { emoji: "🐦", shortcode: "bird", name: "鸟", category: "动物", keywords: ["bird"] },
  { emoji: "🐧", shortcode: "penguin", name: "企鹅", category: "动物", keywords: ["penguin"], popular: true },
  { emoji: "🕊️", shortcode: "dove", name: "鸽子", category: "动物", keywords: ["和平", "dove", "peace"] },
  { emoji: "🦅", shortcode: "eagle", name: "老鹰", category: "动物", keywords: ["eagle"] },
  { emoji: "🦆", shortcode: "duck", name: "鸭子", category: "动物", keywords: ["duck"] },
  { emoji: "🦢", shortcode: "swan", name: "天鹅", category: "动物", keywords: ["swan"] },
  { emoji: "🦉", shortcode: "owl", name: "猫头鹰", category: "动物", keywords: ["owl"] },
  { emoji: "🦤", shortcode: "dodo", name: "渡渡鸟", category: "动物", keywords: ["dodo"] },
  { emoji: "🪶", shortcode: "feather", name: "羽毛", category: "动物", keywords: ["feather"] },
  { emoji: "🦩", shortcode: "flamingo", name: "火烈鸟", category: "动物", keywords: ["flamingo"] },
  { emoji: "🦚", shortcode: "peacock", name: "孔雀", category: "动物", keywords: ["peacock"] },
  { emoji: "🦜", shortcode: "parrot", name: "鹦鹉", category: "动物", keywords: ["parrot"] },
  { emoji: "🐸", shortcode: "frog", name: "青蛙", category: "动物", keywords: ["frog"] },
  { emoji: "🐊", shortcode: "crocodile", name: "鳄鱼", category: "动物", keywords: ["crocodile"] },
  { emoji: "🐢", shortcode: "turtle", name: "乌龟", category: "动物", keywords: ["turtle"] },
  { emoji: "🦎", shortcode: "lizard", name: "蜥蜴", category: "动物", keywords: ["lizard"] },
  { emoji: "🐍", shortcode: "snake", name: "蛇", category: "动物", keywords: ["snake"] },
  { emoji: "🐲", shortcode: "dragon_face", name: "龙头", category: "动物", keywords: ["dragon"] },
  { emoji: "🐉", shortcode: "dragon", name: "龙", category: "动物", keywords: ["dragon"] },
  { emoji: "🦕", shortcode: "sauropod", name: "恐龙", category: "动物", keywords: ["dinosaur", "sauropod"] },
  { emoji: "🦖", shortcode: "t_rex", name: "霸王龙", category: "动物", keywords: ["t-rex", "dinosaur"] },
  { emoji: "🐳", shortcode: "whale", name: "鲸鱼", category: "动物", keywords: ["whale"] },
  { emoji: "🐋", shortcode: "whale2", name: "鲸", category: "动物", keywords: ["whale"] },
  { emoji: "🐬", shortcode: "dolphin", name: "海豚", category: "动物", keywords: ["dolphin"] },
  { emoji: "🦭", shortcode: "seal", name: "海豹", category: "动物", keywords: ["seal"] },
  { emoji: "🐟", shortcode: "fish", name: "鱼", category: "动物", keywords: ["fish"] },
  { emoji: "🐠", shortcode: "tropical_fish", name: "热带鱼", category: "动物", keywords: ["tropical", "fish"] },
  { emoji: "🐡", shortcode: "blowfish", name: "河豚", category: "动物", keywords: ["blowfish", "puffer"] },
  { emoji: "🦈", shortcode: "shark", name: "鲨鱼", category: "动物", keywords: ["shark"] },
  { emoji: "🐙", shortcode: "octopus", name: "章鱼", category: "动物", keywords: ["octopus"] },
  { emoji: "🐚", shortcode: "shell", name: "贝壳", category: "动物", keywords: ["shell"] },
  { emoji: "🐌", shortcode: "snail", name: "蜗牛", category: "动物", keywords: ["snail"] },
  { emoji: "🦋", shortcode: "butterfly", name: "蝴蝶", category: "动物", keywords: ["butterfly"] },
  { emoji: "🐛", shortcode: "bug", name: "毛毛虫", category: "动物", keywords: ["bug"] },
  { emoji: "🐜", shortcode: "ant", name: "蚂蚁", category: "动物", keywords: ["ant"] },
  { emoji: "🐝", shortcode: "bee", name: "蜜蜂", category: "动物", keywords: ["bee", "honeybee"] },
  { emoji: "🪲", shortcode: "beetle", name: "甲虫", category: "动物", keywords: ["beetle"] },
  { emoji: "🐞", shortcode: "lady_beetle", name: "瓢虫", category: "动物", keywords: ["ladybug", "beetle"] },
  { emoji: "🦗", shortcode: "cricket", name: "蟋蟀", category: "动物", keywords: ["cricket"] },
  { emoji: "🪳", shortcode: "cockroach", name: "蟑螂", category: "动物", keywords: ["cockroach"] },
  { emoji: "🕷️", shortcode: "spider", name: "蜘蛛", category: "动物", keywords: ["spider"] },
  { emoji: "🕸️", shortcode: "spider_web", name: "蜘蛛网", category: "动物", keywords: ["spider", "web"] },
  { emoji: "🦂", shortcode: "scorpion", name: "蝎子", category: "动物", keywords: ["scorpion"] },
  { emoji: "🦟", shortcode: "mosquito", name: "蚊子", category: "动物", keywords: ["mosquito"] },
  { emoji: "🪰", shortcode: "fly", name: "苍蝇", category: "动物", keywords: ["fly"] },
  { emoji: "🪱", shortcode: "worm", name: "蠕虫", category: "动物", keywords: ["worm"] },
  { emoji: "🦠", shortcode: "microbe", name: "细菌", category: "动物", keywords: ["病毒", "microbe", "virus"] },

  // ===== 自然 =====
  { emoji: "💐", shortcode: "bouquet", name: "花束", category: "自然", keywords: ["花", "bouquet"] },
  { emoji: "🌸", shortcode: "cherry_blossom", name: "樱花", category: "自然", keywords: ["花", "cherry", "blossom"], popular: true },
  { emoji: "💮", shortcode: "white_flower", name: "白花", category: "自然", keywords: ["flower"] },
  { emoji: "🏵️", shortcode: "rosette", name: "花环", category: "自然", keywords: ["rosette"] },
  { emoji: "🌹", shortcode: "rose", name: "玫瑰", category: "自然", keywords: ["花", "rose"], popular: true },
  { emoji: "🥀", shortcode: "wilted_flower", name: "枯萎的花", category: "自然", keywords: ["wilted", "flower"] },
  { emoji: "🌺", shortcode: "hibiscus", name: "木槿花", category: "自然", keywords: ["hibiscus"] },
  { emoji: "🌻", shortcode: "sunflower", name: "向日葵", category: "自然", keywords: ["sunflower"], popular: true },
  { emoji: "🌼", shortcode: "blossom", name: "小花", category: "自然", keywords: ["blossom", "flower"] },
  { emoji: "🌷", shortcode: "tulip", name: "郁金香", category: "自然", keywords: ["tulip"], popular: true },
  { emoji: "🌱", shortcode: "seedling", name: "幼苗", category: "自然", keywords: ["seedling", "sprout"] },
  { emoji: "🪴", shortcode: "potted_plant", name: "盆栽", category: "自然", keywords: ["potted", "plant"] },
  { emoji: "🌲", shortcode: "evergreen_tree", name: "松树", category: "自然", keywords: ["evergreen", "tree"] },
  { emoji: "🌳", shortcode: "deciduous_tree", name: "树", category: "自然", keywords: ["tree"] },
  { emoji: "🌴", shortcode: "palm_tree", name: "棕榈树", category: "自然", keywords: ["palm", "tree"] },
  { emoji: "🌵", shortcode: "cactus", name: "仙人掌", category: "自然", keywords: ["cactus"] },
  { emoji: "🌾", shortcode: "ear_of_rice", name: "稻穗", category: "自然", keywords: ["rice", "ear"] },
  { emoji: "🌿", shortcode: "herb", name: "草药", category: "自然", keywords: ["herb"] },
  { emoji: "☘️", shortcode: "shamrock", name: "三叶草", category: "自然", keywords: ["shamrock"] },
  { emoji: "🍀", shortcode: "four_leaf_clover", name: "四叶草", category: "自然", keywords: ["幸运", "clover", "luck"] },
  { emoji: "🍁", shortcode: "maple_leaf", name: "枫叶", category: "自然", keywords: ["maple", "leaf"] },
  { emoji: "🍂", shortcode: "fallen_leaf", name: "落叶", category: "自然", keywords: ["fallen", "leaf"] },
  { emoji: "🍃", shortcode: "leaves", name: "叶子", category: "自然", keywords: ["leaves", "wind"] },
  { emoji: "🌍", shortcode: "earth_africa", name: "地球", category: "自然", keywords: ["地球", "earth", "globe"] },
  { emoji: "🌎", shortcode: "earth_americas", name: "地球", category: "自然", keywords: ["earth", "americas"] },
  { emoji: "🌏", shortcode: "earth_asia", name: "地球", category: "自然", keywords: ["earth", "asia"] },
  { emoji: "🌕", shortcode: "full_moon", name: "满月", category: "自然", keywords: ["moon", "full"] },
  { emoji: "🌙", shortcode: "crescent_moon", name: "弯月", category: "自然", keywords: ["moon", "crescent"], popular: true },
  { emoji: "🌞", shortcode: "sun_with_face", name: "太阳", category: "自然", keywords: ["sun"], popular: true },
  { emoji: "⭐", shortcode: "star", name: "星星", category: "自然", keywords: ["star"], popular: true },
  { emoji: "🌟", shortcode: "star2", name: "闪耀的星", category: "自然", keywords: ["star", "glowing"] },
  { emoji: "✨", shortcode: "sparkles", name: "闪光", category: "自然", keywords: ["星星", "sparkles", "sparkle"], popular: true },
  { emoji: "⚡", shortcode: "zap", name: "闪电", category: "自然", keywords: ["闪电", "zap", "lightning"] },
  { emoji: "🔥", shortcode: "fire", name: "火焰", category: "自然", keywords: ["火", "fire", "hot"], popular: true },
  { emoji: "☄️", shortcode: "comet", name: "彗星", category: "自然", keywords: ["comet"] },
  { emoji: "🌈", shortcode: "rainbow", name: "彩虹", category: "自然", keywords: ["rainbow"], popular: true },
  { emoji: "☁️", shortcode: "cloud", name: "云", category: "自然", keywords: ["cloud"] },
  { emoji: "⛅", shortcode: "partly_sunny", name: "多云", category: "自然", keywords: ["partly", "sunny"] },
  { emoji: "🌤️", shortcode: "sun_behind_small_cloud", name: "晴间多云", category: "自然", keywords: ["sun", "cloud"] },
  { emoji: "🌧️", shortcode: "rain", name: "下雨", category: "自然", keywords: ["rain"] },
  { emoji: "⛈️", shortcode: "thunder_cloud_and_rain", name: "雷雨", category: "自然", keywords: ["thunder", "storm"] },
  { emoji: "🌨️", shortcode: "snow", name: "下雪", category: "自然", keywords: ["snow"] },
  { emoji: "❄️", shortcode: "snowflake", name: "雪花", category: "自然", keywords: ["snowflake", "snow"], popular: true },
  { emoji: "☃️", shortcode: "snowman", name: "雪人", category: "自然", keywords: ["snowman"] },
  { emoji: "⛄", shortcode: "snowman_without_snow", name: "雪人", category: "自然", keywords: ["snowman"] },
  { emoji: "🌬️", shortcode: "wind_face", name: "风", category: "自然", keywords: ["wind"] },
  { emoji: "💧", shortcode: "droplet", name: "水滴", category: "自然", keywords: ["droplet", "water"] },
  { emoji: "🌊", shortcode: "ocean", name: "海浪", category: "自然", keywords: ["海", "ocean", "wave"], popular: true },
  { emoji: "🫧", shortcode: "bubbles", name: "泡泡", category: "自然", keywords: ["bubbles"] },

  // ===== 食物 =====
  { emoji: "🍏", shortcode: "green_apple", name: "青苹果", category: "食物", keywords: ["apple", "green"] },
  { emoji: "🍎", shortcode: "apple", name: "苹果", category: "食物", keywords: ["apple", "red"], popular: true },
  { emoji: "🍐", shortcode: "pear", name: "梨", category: "食物", keywords: ["pear"] },
  { emoji: "🍊", shortcode: "tangerine", name: "橘子", category: "食物", keywords: ["orange", "tangerine"] },
  { emoji: "🍋", shortcode: "lemon", name: "柠檬", category: "食物", keywords: ["lemon"] },
  { emoji: "🍌", shortcode: "banana", name: "香蕉", category: "食物", keywords: ["banana"], popular: true },
  { emoji: "🍉", shortcode: "watermelon", name: "西瓜", category: "食物", keywords: ["watermelon"], popular: true },
  { emoji: "🍇", shortcode: "grapes", name: "葡萄", category: "食物", keywords: ["grapes"] },
  { emoji: "🍓", shortcode: "strawberry", name: "草莓", category: "食物", keywords: ["strawberry"], popular: true },
  { emoji: "🫐", shortcode: "blueberries", name: "蓝莓", category: "食物", keywords: ["blueberry", "blueberries"] },
  { emoji: "🍈", shortcode: "melon", name: "哈密瓜", category: "食物", keywords: ["melon"] },
  { emoji: "🍒", shortcode: "cherries", name: "樱桃", category: "食物", keywords: ["cherries", "cherry"] },
  { emoji: "🍑", shortcode: "peach", name: "桃子", category: "食物", keywords: ["peach"] },
  { emoji: "🥭", shortcode: "mango", name: "芒果", category: "食物", keywords: ["mango"] },
  { emoji: "🍍", shortcode: "pineapple", name: "菠萝", category: "食物", keywords: ["pineapple"] },
  { emoji: "🥥", shortcode: "coconut", name: "椰子", category: "食物", keywords: ["coconut"] },
  { emoji: "🥝", shortcode: "kiwi", name: "猕猴桃", category: "食物", keywords: ["kiwi"] },
  { emoji: "🍅", shortcode: "tomato", name: "番茄", category: "食物", keywords: ["tomato"] },
  { emoji: "🍆", shortcode: "eggplant", name: "茄子", category: "食物", keywords: ["eggplant"] },
  { emoji: "🥑", shortcode: "avocado", name: "牛油果", category: "食物", keywords: ["avocado"] },
  { emoji: "🥦", shortcode: "broccoli", name: "西兰花", category: "食物", keywords: ["broccoli"] },
  { emoji: "🥬", shortcode: "leafy_green", name: "蔬菜", category: "食物", keywords: ["leafy", "green"] },
  { emoji: "🥒", shortcode: "cucumber", name: "黄瓜", category: "食物", keywords: ["cucumber"] },
  { emoji: "🌶️", shortcode: "hot_pepper", name: "辣椒", category: "食物", keywords: ["pepper", "hot", "spicy"] },
  { emoji: "🫑", shortcode: "bell_pepper", name: "甜椒", category: "食物", keywords: ["bell", "pepper"] },
  { emoji: "🌽", shortcode: "corn", name: "玉米", category: "食物", keywords: ["corn"] },
  { emoji: "🥕", shortcode: "carrot", name: "胡萝卜", category: "食物", keywords: ["carrot"] },
  { emoji: "🥔", shortcode: "potato", name: "土豆", category: "食物", keywords: ["potato"] },
  { emoji: "🍠", shortcode: "sweet_potato", name: "红薯", category: "食物", keywords: ["sweet", "potato"] },
  { emoji: "🥐", shortcode: "croissant", name: "牛角包", category: "食物", keywords: ["croissant"] },
  { emoji: "🥯", shortcode: "bagel", name: "贝果", category: "食物", keywords: ["bagel"] },
  { emoji: "🍞", shortcode: "bread", name: "面包", category: "食物", keywords: ["bread"], popular: true },
  { emoji: "🥖", shortcode: "baguette_bread", name: "法棍", category: "食物", keywords: ["baguette"] },
  { emoji: "🥨", shortcode: "pretzel", name: "椒盐卷饼", category: "食物", keywords: ["pretzel"] },
  { emoji: "🧀", shortcode: "cheese", name: "奶酪", category: "食物", keywords: ["cheese"] },
  { emoji: "🥚", shortcode: "egg", name: "鸡蛋", category: "食物", keywords: ["egg"] },
  { emoji: "🍳", shortcode: "cooking", name: "煎蛋", category: "食物", keywords: ["cooking", "fried"] },
  { emoji: "🧈", shortcode: "butter", name: "黄油", category: "食物", keywords: ["butter"] },
  { emoji: "🥞", shortcode: "pancakes", name: "松饼", category: "食物", keywords: ["pancakes"] },
  { emoji: "🧇", shortcode: "waffle", name: "华夫饼", category: "食物", keywords: ["waffle"] },
  { emoji: "🥓", shortcode: "bacon", name: "培根", category: "食物", keywords: ["bacon"] },
  { emoji: "🥩", shortcode: "cut_of_meat", name: "肉排", category: "食物", keywords: ["meat", "steak"] },
  { emoji: "🍗", shortcode: "poultry_leg", name: "鸡腿", category: "食物", keywords: ["poultry", "leg"] },
  { emoji: "🍖", shortcode: "meat_on_bone", name: "骨头肉", category: "食物", keywords: ["meat", "bone"] },
  { emoji: "🌭", shortcode: "hotdog", name: "热狗", category: "食物", keywords: ["hotdog"] },
  { emoji: "🍔", shortcode: "hamburger", name: "汉堡", category: "食物", keywords: ["burger", "hamburger"], popular: true },
  { emoji: "🍟", shortcode: "fries", name: "薯条", category: "食物", keywords: ["fries", "chips"], popular: true },
  { emoji: "🍕", shortcode: "pizza", name: "披萨", category: "食物", keywords: ["pizza"], popular: true },
  { emoji: "🥪", shortcode: "sandwich", name: "三明治", category: "食物", keywords: ["sandwich"] },
  { emoji: "🥙", shortcode: "stuffed_flatbread", name: "卷饼", category: "食物", keywords: ["flatbread", "wrap"] },
  { emoji: "🧆", shortcode: "falafel", name: "鹰嘴豆饼", category: "食物", keywords: ["falafel"] },
  { emoji: "🌮", shortcode: "taco", name: "玉米饼", category: "食物", keywords: ["taco"] },
  { emoji: "🌯", shortcode: "burrito", name: "墨西哥卷", category: "食物", keywords: ["burrito"] },
  { emoji: "🥗", shortcode: "green_salad", name: "沙拉", category: "食物", keywords: ["salad"] },
  { emoji: "🥘", shortcode: "shallow_pan_of_food", name: "炖锅", category: "食物", keywords: ["paella", "pan"] },
  { emoji: "🍝", shortcode: "spaghetti", name: "意面", category: "食物", keywords: ["spaghetti", "pasta"] },
  { emoji: "🍜", shortcode: "ramen", name: "拉面", category: "食物", keywords: ["面条", "noodles", "ramen"], popular: true },
  { emoji: "🍲", shortcode: "stew", name: "炖菜", category: "食物", keywords: ["stew"] },
  { emoji: "🍛", shortcode: "curry", name: "咖喱", category: "食物", keywords: ["curry", "rice"] },
  { emoji: "🍣", shortcode: "sushi", name: "寿司", category: "食物", keywords: ["sushi"], popular: true },
  { emoji: "🍱", shortcode: "bento", name: "便当", category: "食物", keywords: ["bento", "box"] },
  { emoji: "🥟", shortcode: "dumpling", name: "饺子", category: "食物", keywords: ["dumpling", "饺子"] },
  { emoji: "🦪", shortcode: "oyster", name: "生蚝", category: "食物", keywords: ["oyster"] },
  { emoji: "🍤", shortcode: "fried_shrimp", name: "炸虾", category: "食物", keywords: ["fried", "shrimp"] },
  { emoji: "🍙", shortcode: "rice_ball", name: "饭团", category: "食物", keywords: ["rice", "ball"] },
  { emoji: "🍚", shortcode: "rice", name: "米饭", category: "食物", keywords: ["rice", "cooked"] },
  { emoji: "🍘", shortcode: "rice_cracker", name: "米饼", category: "食物", keywords: ["rice", "cracker"] },
  { emoji: "🍥", shortcode: "fish_cake", name: "鱼糕", category: "食物", keywords: ["fish", "cake"] },
  { emoji: "🥠", shortcode: "fortune_cookie", name: "幸运饼干", category: "食物", keywords: ["fortune", "cookie"] },
  { emoji: "🥡", shortcode: "takeout_box", name: "外卖盒", category: "食物", keywords: ["takeout", "box"] },
  { emoji: "🍢", shortcode: "oden", name: "关东煮", category: "食物", keywords: ["oden"] },
  { emoji: "🍡", shortcode: "dango", name: "团子", category: "食物", keywords: ["dango"] },
  { emoji: "🍧", shortcode: "shaved_ice", name: "刨冰", category: "食物", keywords: ["shaved", "ice"] },
  { emoji: "🍨", shortcode: "ice_cream", name: "冰淇淋", category: "食物", keywords: ["ice", "cream"] },
  { emoji: "🍦", shortcode: "icecream", name: "甜筒", category: "食物", keywords: ["icecream", "cone"] },
  { emoji: "🍩", shortcode: "doughnut", name: "甜甜圈", category: "食物", keywords: ["doughnut", "donut"] },
  { emoji: "🍪", shortcode: "cookie", name: "曲奇", category: "食物", keywords: ["cookie"] },
  { emoji: "🎂", shortcode: "birthday", name: "生日蛋糕", category: "食物", keywords: ["生日", "birthday", "cake"] },
  { emoji: "🍰", shortcode: "cake", name: "蛋糕", category: "食物", keywords: ["cake", "shortcake"] },
  { emoji: "🧁", shortcode: "cupcake", name: "纸杯蛋糕", category: "食物", keywords: ["cupcake"] },
  { emoji: "🥧", shortcode: "pie", name: "派", category: "食物", keywords: ["pie"] },
  { emoji: "🍫", shortcode: "chocolate_bar", name: "巧克力", category: "食物", keywords: ["chocolate"] },
  { emoji: "🍬", shortcode: "candy", name: "糖果", category: "食物", keywords: ["candy"] },
  { emoji: "🍭", shortcode: "lollipop", name: "棒棒糖", category: "食物", keywords: ["lollipop"] },
  { emoji: "🍮", shortcode: "custard", name: "布丁", category: "食物", keywords: ["custard"] },
  { emoji: "🍯", shortcode: "honey_pot", name: "蜂蜜", category: "食物", keywords: ["honey"] },
  { emoji: "🍼", shortcode: "baby_bottle", name: "奶瓶", category: "食物", keywords: ["baby", "bottle"] },
  { emoji: "🥛", shortcode: "milk_glass", name: "牛奶", category: "食物", keywords: ["milk"] },
  { emoji: "☕", shortcode: "coffee", name: "咖啡", category: "食物", keywords: ["coffee", "hot"], popular: true },
  { emoji: "🫖", shortcode: "teapot", name: "茶壶", category: "食物", keywords: ["teapot"] },
  { emoji: "🍵", shortcode: "tea", name: "茶", category: "食物", keywords: ["tea"], popular: true },
  { emoji: "🧃", shortcode: "juice_box", name: "果汁盒", category: "食物", keywords: ["juice", "box"] },
  { emoji: "🥤", shortcode: "cup_with_straw", name: "饮料", category: "食物", keywords: ["cup", "straw", "soda"] },
  { emoji: "🧋", shortcode: "bubble_tea", name: "奶茶", category: "食物", keywords: ["奶茶", "bubble", "tea", "milk"] },
  { emoji: "🍶", shortcode: "sake", name: "清酒", category: "食物", keywords: ["sake"] },
  { emoji: "🍾", shortcode: "champagne", name: "香槟", category: "食物", keywords: ["champagne", "bottle"] },
  { emoji: "🍷", shortcode: "wine_glass", name: "红酒", category: "食物", keywords: ["wine"] },
  { emoji: "🍸", shortcode: "cocktail", name: "鸡尾酒", category: "食物", keywords: ["cocktail"] },
  { emoji: "🍹", shortcode: "tropical_drink", name: "果汁", category: "食物", keywords: ["tropical", "drink"] },
  { emoji: "🍺", shortcode: "beer", name: "啤酒", category: "食物", keywords: ["beer"], popular: true },
  { emoji: "🍻", shortcode: "beers", name: "干杯", category: "食物", keywords: ["cheers", "beers"], popular: true },
  { emoji: "🥂", shortcode: "clinking_glasses", name: "碰杯", category: "食物", keywords: ["clinking", "glasses", "cheers"] },
  { emoji: "🥃", shortcode: "tumbler_glass", name: "威士忌", category: "食物", keywords: ["tumbler", "whisky"] },
  { emoji: "🥢", shortcode: "chopsticks", name: "筷子", category: "食物", keywords: ["chopsticks"] },
  { emoji: "🍽️", shortcode: "fork_and_knife_with_plate", name: "餐具", category: "食物", keywords: ["fork", "knife", "plate"] },
  { emoji: "🍴", shortcode: "fork_and_knife", name: "刀叉", category: "食物", keywords: ["fork", "knife"] },
  { emoji: "🥄", shortcode: "spoon", name: "勺子", category: "食物", keywords: ["spoon"] },
  { emoji: "🔪", shortcode: "knife", name: "菜刀", category: "食物", keywords: ["knife", "cut"] },

  // ===== 出行 =====
  { emoji: "🚗", shortcode: "red_car", name: "汽车", category: "出行", keywords: ["car", "auto"], popular: true },
  { emoji: "🚕", shortcode: "taxi", name: "出租车", category: "出行", keywords: ["taxi", "cab"] },
  { emoji: "🚙", shortcode: "blue_car", name: "越野车", category: "出行", keywords: ["car", "suv"] },
  { emoji: "🚌", shortcode: "bus", name: "公交车", category: "出行", keywords: ["bus"] },
  { emoji: "🚎", shortcode: "trolleybus", name: "无轨电车", category: "出行", keywords: ["trolleybus"] },
  { emoji: "🏎️", shortcode: "racing_car", name: "赛车", category: "出行", keywords: ["racing", "car"] },
  { emoji: "🚓", shortcode: "police_car", name: "警车", category: "出行", keywords: ["police", "car"] },
  { emoji: "🚑", shortcode: "ambulance", name: "救护车", category: "出行", keywords: ["ambulance"] },
  { emoji: "🚒", shortcode: "fire_engine", name: "消防车", category: "出行", keywords: ["fire", "engine"] },
  { emoji: "🚐", shortcode: "minibus", name: "面包车", category: "出行", keywords: ["minibus"] },
  { emoji: "🚚", shortcode: "truck", name: "卡车", category: "出行", keywords: ["truck"] },
  { emoji: "🚛", shortcode: "articulated_lorry", name: "挂车", category: "出行", keywords: ["lorry", "truck"] },
  { emoji: "🚜", shortcode: "tractor", name: "拖拉机", category: "出行", keywords: ["tractor"] },
  { emoji: "🏍️", shortcode: "motorcycle", name: "摩托车", category: "出行", keywords: ["motorcycle", "bike"] },
  { emoji: "🚲", shortcode: "bike", name: "自行车", category: "出行", keywords: ["bicycle", "bike"], popular: true },
  { emoji: "🛴", shortcode: "kick_scooter", name: "滑板车", category: "出行", keywords: ["scooter"] },
  { emoji: "🚨", shortcode: "rotating_light", name: "警灯", category: "出行", keywords: ["rotating", "light", "siren"] },
  { emoji: "🚔", shortcode: "oncoming_police_car", name: "警车", category: "出行", keywords: ["police", "car"] },
  { emoji: "🚍", shortcode: "oncoming_bus", name: "公交车", category: "出行", keywords: ["bus"] },
  { emoji: "🚘", shortcode: "oncoming_automobile", name: "汽车", category: "出行", keywords: ["car"] },
  { emoji: "🚖", shortcode: "oncoming_taxi", name: "出租车", category: "出行", keywords: ["taxi"] },
  { emoji: "🚡", shortcode: "aerial_tramway", name: "缆车", category: "出行", keywords: ["aerial", "tramway"] },
  { emoji: "🚠", shortcode: "mountain_cableway", name: "登山缆车", category: "出行", keywords: ["cableway", "mountain"] },
  { emoji: "🚟", shortcode: "suspension_railway", name: "悬挂铁路", category: "出行", keywords: ["suspension", "railway"] },
  { emoji: "🚃", shortcode: "railway_car", name: "火车车厢", category: "出行", keywords: ["railway", "car"] },
  { emoji: "🚋", shortcode: "train", name: "有轨电车", category: "出行", keywords: ["train", "tram"] },
  { emoji: "🚞", shortcode: "mountain_railway", name: "山地火车", category: "出行", keywords: ["mountain", "railway"] },
  { emoji: "🚝", shortcode: "monorail", name: "单轨列车", category: "出行", keywords: ["monorail"] },
  { emoji: "🚄", shortcode: "bullettrain_side", name: "高铁", category: "出行", keywords: ["bullet", "train", "高铁"], popular: true },
  { emoji: "🚅", shortcode: "bullettrain_front", name: "高铁车头", category: "出行", keywords: ["bullet", "train"] },
  { emoji: "🚈", shortcode: "light_rail", name: "轻轨", category: "出行", keywords: ["light", "rail"] },
  { emoji: "🚂", shortcode: "steam_locomotive", name: "蒸汽火车", category: "出行", keywords: ["steam", "locomotive"] },
  { emoji: "🚆", shortcode: "train2", name: "火车", category: "出行", keywords: ["train"] },
  { emoji: "🚇", shortcode: "metro", name: "地铁", category: "出行", keywords: ["metro", "subway"] },
  { emoji: "🚊", shortcode: "tram", name: "有轨电车", category: "出行", keywords: ["tram"] },
  { emoji: "🚉", shortcode: "station", name: "车站", category: "出行", keywords: ["station"] },
  { emoji: "✈️", shortcode: "airplane", name: "飞机", category: "出行", keywords: ["plane", "airplane", "flight"], popular: true },
  { emoji: "🛫", shortcode: "airplane_departure", name: "起飞", category: "出行", keywords: ["departure", "takeoff"] },
  { emoji: "🛬", shortcode: "airplane_arriving", name: "降落", category: "出行", keywords: ["arrival", "landing"] },
  { emoji: "🪂", shortcode: "parachute", name: "降落伞", category: "出行", keywords: ["parachute"] },
  { emoji: "💺", shortcode: "seat", name: "座位", category: "出行", keywords: ["seat"] },
  { emoji: "🚁", shortcode: "helicopter", name: "直升机", category: "出行", keywords: ["helicopter"] },
  { emoji: "🚀", shortcode: "rocket", name: "火箭", category: "出行", keywords: ["rocket", "launch"], popular: true },
  { emoji: "🛸", shortcode: "flying_saucer", name: "飞碟", category: "出行", keywords: ["flying", "saucer", "ufo"] },
  { emoji: "🛶", shortcode: "canoe", name: "独木舟", category: "出行", keywords: ["canoe"] },
  { emoji: "⛵", shortcode: "sailboat", name: "帆船", category: "出行", keywords: ["sailboat", "boat"] },
  { emoji: "🚤", shortcode: "speedboat", name: "快艇", category: "出行", keywords: ["speedboat"] },
  { emoji: "🛳️", shortcode: "passenger_ship", name: "客轮", category: "出行", keywords: ["ship", "passenger"] },
  { emoji: "⛴️", shortcode: "ferry", name: "渡轮", category: "出行", keywords: ["ferry"] },
  { emoji: "🛥️", shortcode: "motor_boat", name: "摩托艇", category: "出行", keywords: ["motor", "boat"] },
  { emoji: "⚓", shortcode: "anchor", name: "锚", category: "出行", keywords: ["anchor"] },
  { emoji: "🚧", shortcode: "construction", name: "施工", category: "出行", keywords: ["construction", "barrier"] },
  { emoji: "⛽", shortcode: "fuelpump", name: "加油站", category: "出行", keywords: ["fuel", "pump"] },
  { emoji: "🚏", shortcode: "busstop", name: "公交站", category: "出行", keywords: ["bus", "stop"] },
  { emoji: "🗺️", shortcode: "world_map", name: "地图", category: "出行", keywords: ["world", "map"] },
  { emoji: "🗿", shortcode: "moai", name: "摩艾石像", category: "出行", keywords: ["moai", "statue"] },
  { emoji: "🗽", shortcode: "statue_of_liberty", name: "自由女神", category: "出行", keywords: ["statue", "liberty"] },
  { emoji: "🗼", shortcode: "tokyo_tower", name: "东京塔", category: "出行", keywords: ["tokyo", "tower"] },
  { emoji: "🏰", shortcode: "european_castle", name: "城堡", category: "出行", keywords: ["castle"], popular: true },
  { emoji: "🏯", shortcode: "japanese_castle", name: "日式城堡", category: "出行", keywords: ["castle"] },
  { emoji: "🏟️", shortcode: "stadium", name: "体育场", category: "出行", keywords: ["stadium"] },
  { emoji: "🎡", shortcode: "ferris_wheel", name: "摩天轮", category: "出行", keywords: ["ferris", "wheel"] },
  { emoji: "🎢", shortcode: "roller_coaster", name: "过山车", category: "出行", keywords: ["roller", "coaster"] },
  { emoji: "🎠", shortcode: "carousel_horse", name: "旋转木马", category: "出行", keywords: ["carousel", "horse"] },
  { emoji: "⛲", shortcode: "fountain", name: "喷泉", category: "出行", keywords: ["fountain"] },
  { emoji: "⛺", shortcode: "tent", name: "帐篷", category: "出行", keywords: ["tent", "camping"] },
  { emoji: "🌁", shortcode: "foggy", name: "雾", category: "出行", keywords: ["foggy", "fog"] },
  { emoji: "🌃", shortcode: "night_with_stars", name: "星空夜景", category: "出行", keywords: ["night", "stars"] },
  { emoji: "🏙️", shortcode: "cityscape", name: "城市", category: "出行", keywords: ["city", "cityscape"] },
  { emoji: "🌄", shortcode: "sunrise_over_mountains", name: "日出", category: "出行", keywords: ["sunrise", "mountains"] },
  { emoji: "🌅", shortcode: "sunrise", name: "日出", category: "出行", keywords: ["sunrise"] },
  { emoji: "🌆", shortcode: "city_sunset", name: "城市黄昏", category: "出行", keywords: ["city", "sunset"] },
  { emoji: "🌇", shortcode: "sunset", name: "日落", category: "出行", keywords: ["sunset"] },
  { emoji: "🌉", shortcode: "bridge_at_night", name: "夜景桥", category: "出行", keywords: ["bridge", "night"] },
  { emoji: "♨️", shortcode: "hotsprings", name: "温泉", category: "出行", keywords: ["hotsprings", "onsen"] },
  { emoji: "🏞️", shortcode: "national_park", name: "国家公园", category: "出行", keywords: ["national", "park"] },
  { emoji: "🛤️", shortcode: "railway_track", name: "铁轨", category: "出行", keywords: ["railway", "track"] },
  { emoji: "🛣️", shortcode: "motorway", name: "高速公路", category: "出行", keywords: ["motorway", "highway"] },

  // ===== 活动 =====
  { emoji: "⚽", shortcode: "soccer", name: "足球", category: "活动", keywords: ["soccer", "football"], popular: true },
  { emoji: "🏀", shortcode: "basketball", name: "篮球", category: "活动", keywords: ["basketball"], popular: true },
  { emoji: "🏈", shortcode: "football", name: "橄榄球", category: "活动", keywords: ["football", "american"] },
  { emoji: "⚾", shortcode: "baseball", name: "棒球", category: "活动", keywords: ["baseball"] },
  { emoji: "🥎", shortcode: "softball", name: "垒球", category: "活动", keywords: ["softball"] },
  { emoji: "🎾", shortcode: "tennis", name: "网球", category: "活动", keywords: ["tennis"] },
  { emoji: "🏐", shortcode: "volleyball", name: "排球", category: "活动", keywords: ["volleyball"] },
  { emoji: "🏉", shortcode: "rugby_football", name: "英式橄榄球", category: "活动", keywords: ["rugby"] },
  { emoji: "🥏", shortcode: "flying_disc", name: "飞盘", category: "活动", keywords: ["flying", "disc"] },
  { emoji: "🎱", shortcode: "pool_8_ball", name: "台球", category: "活动", keywords: ["pool", "billiard"] },
  { emoji: "🏓", shortcode: "ping_pong", name: "乒乓球", category: "活动", keywords: ["ping", "pong", "table tennis"] },
  { emoji: "🏸", shortcode: "badminton", name: "羽毛球", category: "活动", keywords: ["badminton"] },
  { emoji: "🏒", shortcode: "ice_hockey", name: "冰球", category: "活动", keywords: ["ice", "hockey"] },
  { emoji: "🏑", shortcode: "field_hockey", name: "曲棍球", category: "活动", keywords: ["field", "hockey"] },
  { emoji: "🥍", shortcode: "lacrosse", name: "长曲棍球", category: "活动", keywords: ["lacrosse"] },
  { emoji: "🏏", shortcode: "cricket_game", name: "板球", category: "活动", keywords: ["cricket"] },
  { emoji: "🥅", shortcode: "goal_net", name: "球门", category: "活动", keywords: ["goal", "net"] },
  { emoji: "⛳", shortcode: "golf", name: "高尔夫球", category: "活动", keywords: ["golf"] },
  { emoji: "🪀", shortcode: "yo_yo", name: "悠悠球", category: "活动", keywords: ["yo-yo"] },
  { emoji: "🏹", shortcode: "bow_and_arrow", name: "射箭", category: "活动", keywords: ["bow", "arrow"] },
  { emoji: "🎣", shortcode: "fishing_pole_and_fish", name: "钓鱼", category: "活动", keywords: ["fishing"] },
  { emoji: "🥊", shortcode: "boxing_glove", name: "拳击手套", category: "活动", keywords: ["boxing"] },
  { emoji: "🥋", shortcode: "martial_arts_uniform", name: "武术服", category: "活动", keywords: ["martial", "arts"] },
  { emoji: "🎽", shortcode: "running_shirt_with_sash", name: "跑步衫", category: "活动", keywords: ["running", "shirt"] },
  { emoji: "🛹", shortcode: "skateboard", name: "滑板", category: "活动", keywords: ["skateboard"] },
  { emoji: "🛼", shortcode: "roller_skate", name: "轮滑", category: "活动", keywords: ["roller", "skate"] },
  { emoji: "🛷", shortcode: "sled", name: "雪橇", category: "活动", keywords: ["sled"] },
  { emoji: "⛸️", shortcode: "ice_skate", name: "滑冰", category: "活动", keywords: ["ice", "skate"] },
  { emoji: "🎿", shortcode: "ski", name: "滑雪", category: "活动", keywords: ["ski"] },
  { emoji: "🎯", shortcode: "dart", name: "飞镖", category: "活动", keywords: ["dart", "target"] },
  { emoji: "🎮", shortcode: "video_game", name: "游戏手柄", category: "活动", keywords: ["video", "game", "console"], popular: true },
  { emoji: "🕹️", shortcode: "joystick", name: "摇杆", category: "活动", keywords: ["joystick"] },
  { emoji: "🎲", shortcode: "dice", name: "骰子", category: "活动", keywords: ["dice"] },
  { emoji: "♠️", shortcode: "spades", name: "黑桃", category: "活动", keywords: ["spades"] },
  { emoji: "♥️", shortcode: "hearts", name: "红桃", category: "活动", keywords: ["hearts"] },
  { emoji: "♦️", shortcode: "diamonds", name: "方块", category: "活动", keywords: ["diamonds"] },
  { emoji: "♣️", shortcode: "clubs", name: "梅花", category: "活动", keywords: ["clubs"] },
  { emoji: "🃏", shortcode: "black_joker", name: "小丑牌", category: "活动", keywords: ["joker"] },
  { emoji: "🀄", shortcode: "mahjong", name: "麻将", category: "活动", keywords: ["mahjong"] },
  { emoji: "🎴", shortcode: "flower_playing_cards", name: "花牌", category: "活动", keywords: ["flower", "cards"] },
  { emoji: "🎭", shortcode: "performing_arts", name: "戏剧", category: "活动", keywords: ["performing", "arts"] },
  { emoji: "🖼️", shortcode: "framed_picture", name: "画框", category: "活动", keywords: ["framed", "picture"] },
  { emoji: "🎨", shortcode: "art", name: "调色板", category: "活动", keywords: ["art", "palette"] },
  { emoji: "🧵", shortcode: "thread", name: "线", category: "活动", keywords: ["thread"] },
  { emoji: "🪡", shortcode: "sewing_needle", name: "缝衣针", category: "活动", keywords: ["sewing", "needle"] },
  { emoji: "🧶", shortcode: "yarn", name: "毛线", category: "活动", keywords: ["yarn"] },
  { emoji: "🪢", shortcode: "knot", name: "绳结", category: "活动", keywords: ["knot"] },
  { emoji: "🎬", shortcode: "clapper", name: "场记板", category: "活动", keywords: ["movie", "clapper"] },
  { emoji: "🎤", shortcode: "microphone", name: "麦克风", category: "活动", keywords: ["microphone", "mic"] },
  { emoji: "🎧", shortcode: "headphones", name: "耳机", category: "活动", keywords: ["headphones"] },
  { emoji: "🎷", shortcode: "saxophone", name: "萨克斯", category: "活动", keywords: ["saxophone"] },
  { emoji: "🎸", shortcode: "guitar", name: "吉他", category: "活动", keywords: ["guitar"] },
  { emoji: "🎹", shortcode: "musical_keyboard", name: "钢琴键盘", category: "活动", keywords: ["musical", "keyboard"] },
  { emoji: "🎺", shortcode: "trumpet", name: "小号", category: "活动", keywords: ["trumpet"] },
  { emoji: "🎻", shortcode: "violin", name: "小提琴", category: "活动", keywords: ["violin"] },
  { emoji: "🪕", shortcode: "banjo", name: "班卓琴", category: "活动", keywords: ["banjo"] },
  { emoji: "🥁", shortcode: "drum", name: "鼓", category: "活动", keywords: ["drum"] },
  { emoji: "🎪", shortcode: "circus_tent", name: "马戏团", category: "活动", keywords: ["circus", "tent"] },
  { emoji: "🎟️", shortcode: "admission_tickets", name: "门票", category: "活动", keywords: ["admission", "tickets"] },
  { emoji: "🎫", shortcode: "ticket", name: "票", category: "活动", keywords: ["ticket"] },
  { emoji: "🏆", shortcode: "trophy", name: "奖杯", category: "活动", keywords: ["trophy", "奖"], popular: true },
  { emoji: "🏅", shortcode: "sports_medal", name: "奖牌", category: "活动", keywords: ["medal"] },
  { emoji: "🥇", shortcode: "first_place_medal", name: "金牌", category: "活动", keywords: ["first", "gold"] },
  { emoji: "🥈", shortcode: "second_place_medal", name: "银牌", category: "活动", keywords: ["second", "silver"] },
  { emoji: "🥉", shortcode: "third_place_medal", name: "铜牌", category: "活动", keywords: ["third", "bronze"] },
  { emoji: "🎗️", shortcode: "reminder_ribbon", name: "纪念带", category: "活动", keywords: ["reminder", "ribbon"] },
  { emoji: "🎀", shortcode: "ribbon", name: "蝴蝶结", category: "活动", keywords: ["ribbon"] },
  { emoji: "🎁", shortcode: "gift", name: "礼物", category: "活动", keywords: ["gift", "present"], popular: true },
  { emoji: "🎊", shortcode: "confetti_ball", name: "彩带球", category: "活动", keywords: ["confetti"] },
  { emoji: "🎉", shortcode: "tada", name: "庆祝彩带", category: "活动", keywords: ["庆祝", "party", "tada", "congrats"], popular: true },
  { emoji: "🎎", shortcode: "dolls", name: "人偶", category: "活动", keywords: ["dolls"] },
  { emoji: "🪄", shortcode: "magic_wand", name: "魔法棒", category: "活动", keywords: ["magic", "wand"] },
  { emoji: "🧧", shortcode: "red_envelope", name: "红包", category: "活动", keywords: ["红包", "red", "envelope", "红包"], popular: true },
  { emoji: "🎐", shortcode: "wind_chime", name: "风铃", category: "活动", keywords: ["wind", "chime"] },
  { emoji: "🎏", shortcode: "flags", name: "鲤鱼旗", category: "活动", keywords: ["flags", "carp"] },
  { emoji: "🎌", shortcode: "crossed_flags", name: "交叉旗", category: "活动", keywords: ["crossed", "flags"] },
  { emoji: "🏁", shortcode: "checkered_flag", name: "终点旗", category: "活动", keywords: ["checkered", "flag", "finish"] },
  { emoji: "🚩", shortcode: "triangular_flag_on_post", name: "红旗", category: "活动", keywords: ["triangular", "flag"] },
  { emoji: "🏳️", shortcode: "white_flag", name: "白旗", category: "活动", keywords: ["white", "flag"] },
  { emoji: "🏴", shortcode: "black_flag", name: "黑旗", category: "活动", keywords: ["black", "flag"] },
  { emoji: "🏳️‍🌈", shortcode: "rainbow_flag", name: "彩虹旗", category: "活动", keywords: ["rainbow", "flag"] },
  { emoji: "🏴‍☠️", shortcode: "pirate_flag", name: "海盗旗", category: "活动", keywords: ["pirate", "flag"] },
  { emoji: "🎍", shortcode: "bamboo", name: "竹子", category: "活动", keywords: ["bamboo"] },
  { emoji: "🎋", shortcode: "tanabata_tree", name: "七夕树", category: "活动", keywords: ["tanabata", "tree"] },
  { emoji: "🪅", shortcode: "pinata", name: "皮纳塔", category: "活动", keywords: ["pinata"] },
  { emoji: "🪆", shortcode: "nesting_dolls", name: "套娃", category: "活动", keywords: ["nesting", "dolls"] },
  { emoji: "🖌️", shortcode: "paintbrush", name: "画笔", category: "活动", keywords: ["paintbrush"] },
  { emoji: "🖍️", shortcode: "crayon", name: "蜡笔", category: "活动", keywords: ["crayon"] },
  { emoji: "✏️", shortcode: "pencil2", name: "铅笔", category: "活动", keywords: ["pencil"] },
  { emoji: "✒️", shortcode: "black_nib", name: "钢笔尖", category: "活动", keywords: ["nib", "pen"] },
  { emoji: "🖊️", shortcode: "pen", name: "钢笔", category: "活动", keywords: ["pen"] },
  { emoji: "🖋️", shortcode: "fountain_pen", name: "钢笔", category: "活动", keywords: ["fountain", "pen"] },
  { emoji: "📝", shortcode: "memo", name: "便签", category: "活动", keywords: ["memo", "note"], popular: true },

  // ===== 物体 =====
  { emoji: "⌚", shortcode: "watch", name: "手表", category: "物体", keywords: ["watch"] },
  { emoji: "📱", shortcode: "iphone", name: "手机", category: "物体", keywords: ["手机", "phone", "mobile", "smartphone"], popular: true },
  { emoji: "📲", shortcode: "calling", name: "来电", category: "物体", keywords: ["calling", "phone"] },
  { emoji: "💻", shortcode: "computer", name: "笔记本电脑", category: "物体", keywords: ["computer", "laptop"], popular: true },
  { emoji: "⌨️", shortcode: "keyboard", name: "键盘", category: "物体", keywords: ["keyboard"] },
  { emoji: "🖥️", shortcode: "desktop_computer", name: "台式电脑", category: "物体", keywords: ["desktop", "computer"] },
  { emoji: "🖨️", shortcode: "printer", name: "打印机", category: "物体", keywords: ["printer"] },
  { emoji: "🖱️", shortcode: "mouse_three_button", name: "鼠标", category: "物体", keywords: ["mouse"] },
  { emoji: "🖲️", shortcode: "trackball", name: "轨迹球", category: "物体", keywords: ["trackball"] },
  { emoji: "💾", shortcode: "floppy_disk", name: "软盘", category: "物体", keywords: ["floppy", "disk"] },
  { emoji: "💿", shortcode: "cd", name: "光盘", category: "物体", keywords: ["cd", "optical"] },
  { emoji: "📀", shortcode: "dvd", name: "DVD", category: "物体", keywords: ["dvd"] },
  { emoji: "🧮", shortcode: "abacus", name: "算盘", category: "物体", keywords: ["abacus"] },
  { emoji: "📷", shortcode: "camera", name: "相机", category: "物体", keywords: ["camera", "photo"], popular: true },
  { emoji: "📸", shortcode: "camera_with_flash", name: "闪光灯相机", category: "物体", keywords: ["camera", "flash"] },
  { emoji: "📹", shortcode: "video_camera", name: "摄像机", category: "物体", keywords: ["video", "camera"] },
  { emoji: "🎥", shortcode: "movie_camera", name: "电影摄影机", category: "物体", keywords: ["movie", "camera"] },
  { emoji: "📽️", shortcode: "film_projector", name: "放映机", category: "物体", keywords: ["film", "projector"] },
  { emoji: "🎞️", shortcode: "film_frames", name: "胶片", category: "物体", keywords: ["film", "frames"] },
  { emoji: "📞", shortcode: "telephone_receiver", name: "电话听筒", category: "物体", keywords: ["telephone", "receiver"] },
  { emoji: "☎️", shortcode: "telephone", name: "电话", category: "物体", keywords: ["telephone", "phone"] },
  { emoji: "📟", shortcode: "pager", name: "传呼机", category: "物体", keywords: ["pager"] },
  { emoji: "📠", shortcode: "fax", name: "传真机", category: "物体", keywords: ["fax"] },
  { emoji: "📺", shortcode: "tv", name: "电视", category: "物体", keywords: ["tv", "television"] },
  { emoji: "📻", shortcode: "radio", name: "收音机", category: "物体", keywords: ["radio"] },
  { emoji: "🎙️", shortcode: "studio_microphone", name: "录音麦克风", category: "物体", keywords: ["studio", "microphone"] },
  { emoji: "🎚️", shortcode: "level_slider", name: "音量滑块", category: "物体", keywords: ["level", "slider"] },
  { emoji: "🎛️", shortcode: "control_knobs", name: "旋钮", category: "物体", keywords: ["control", "knobs"] },
  { emoji: "🧭", shortcode: "compass", name: "指南针", category: "物体", keywords: ["compass"] },
  { emoji: "⏱️", shortcode: "stopwatch", name: "秒表", category: "物体", keywords: ["stopwatch"] },
  { emoji: "⏲️", shortcode: "timer_clock", name: "计时器", category: "物体", keywords: ["timer"] },
  { emoji: "⏰", shortcode: "alarm_clock", name: "闹钟", category: "物体", keywords: ["alarm", "clock"] },
  { emoji: "🕰️", shortcode: "mantlepiece_clock", name: "座钟", category: "物体", keywords: ["mantlepiece", "clock"] },
  { emoji: "⌛", shortcode: "hourglass", name: "沙漏", category: "物体", keywords: ["hourglass"] },
  { emoji: "⏳", shortcode: "hourglass_flowing_sand", name: "流沙沙漏", category: "物体", keywords: ["hourglass", "flowing"] },
  { emoji: "📡", shortcode: "satellite", name: "卫星天线", category: "物体", keywords: ["satellite", "antenna"] },
  { emoji: "🔋", shortcode: "battery", name: "电池", category: "物体", keywords: ["battery"] },
  { emoji: "🔌", shortcode: "electric_plug", name: "插头", category: "物体", keywords: ["electric", "plug"] },
  { emoji: "💡", shortcode: "bulb", name: "灯泡", category: "物体", keywords: ["bulb", "light", "idea"], popular: true },
  { emoji: "🔦", shortcode: "flashlight", name: "手电筒", category: "物体", keywords: ["flashlight"] },
  { emoji: "🕯️", shortcode: "candle", name: "蜡烛", category: "物体", keywords: ["candle"] },
  { emoji: "🪔", shortcode: "diya_lamp", name: "油灯", category: "物体", keywords: ["diya", "lamp"] },
  { emoji: "💸", shortcode: "money_with_wings", name: "钱飞走", category: "物体", keywords: ["money", "wings"] },
  { emoji: "💵", shortcode: "dollar", name: "美元", category: "物体", keywords: ["dollar"] },
  { emoji: "💴", shortcode: "yen", name: "日元", category: "物体", keywords: ["yen"] },
  { emoji: "💶", shortcode: "euro", name: "欧元", category: "物体", keywords: ["euro"] },
  { emoji: "💷", shortcode: "pound", name: "英镑", category: "物体", keywords: ["pound"] },
  { emoji: "💰", shortcode: "moneybag", name: "钱袋", category: "物体", keywords: ["money", "bag"], popular: true },
  { emoji: "💳", shortcode: "credit_card", name: "银行卡", category: "物体", keywords: ["credit", "card"] },
  { emoji: "🧾", shortcode: "receipt", name: "收据", category: "物体", keywords: ["receipt"] },
  { emoji: "💎", shortcode: "gem", name: "宝石", category: "物体", keywords: ["gem", "diamond"] },
  { emoji: "⚖️", shortcode: "balance_scale", name: "天平", category: "物体", keywords: ["balance", "scale"] },
  { emoji: "🧰", shortcode: "toolbox", name: "工具箱", category: "物体", keywords: ["toolbox"] },
  { emoji: "🪛", shortcode: "screwdriver", name: "螺丝刀", category: "物体", keywords: ["screwdriver"] },
  { emoji: "🔧", shortcode: "wrench", name: "扳手", category: "物体", keywords: ["wrench"] },
  { emoji: "🔨", shortcode: "hammer", name: "锤子", category: "物体", keywords: ["hammer"] },
  { emoji: "⚒️", shortcode: "hammer_and_pick", name: "锤镐", category: "物体", keywords: ["hammer", "pick"] },
  { emoji: "🛠️", shortcode: "hammer_and_wrench", name: "锤扳手", category: "物体", keywords: ["hammer", "wrench"] },
  { emoji: "⛏️", shortcode: "pick", name: "镐", category: "物体", keywords: ["pick"] },
  { emoji: "🔩", shortcode: "nut_and_bolt", name: "螺母螺栓", category: "物体", keywords: ["nut", "bolt"] },
  { emoji: "⚙️", shortcode: "gear", name: "齿轮", category: "物体", keywords: ["gear"] },
  { emoji: "🪤", shortcode: "mouse_trap", name: "捕鼠夹", category: "物体", keywords: ["mouse", "trap"] },
  { emoji: "🧲", shortcode: "magnet", name: "磁铁", category: "物体", keywords: ["magnet"] },
  { emoji: "⚗️", shortcode: "alembic", name: "蒸馏器", category: "物体", keywords: ["alembic"] },
  { emoji: "🧪", shortcode: "test_tube", name: "试管", category: "物体", keywords: ["test", "tube", "lab"] },
  { emoji: "🧫", shortcode: "petri_dish", name: "培养皿", category: "物体", keywords: ["petri", "dish"] },
  { emoji: "🧬", shortcode: "dna", name: "DNA", category: "物体", keywords: ["dna"] },
  { emoji: "🔬", shortcode: "microscope", name: "显微镜", category: "物体", keywords: ["microscope"] },
  { emoji: "🔭", shortcode: "telescope", name: "望远镜", category: "物体", keywords: ["telescope"] },
  { emoji: "🩸", shortcode: "drop_of_blood", name: "血滴", category: "物体", keywords: ["drop", "blood"] },
  { emoji: "🩹", shortcode: "adhesive_bandage", name: "创可贴", category: "物体", keywords: ["adhesive", "bandage"] },
  { emoji: "🩺", shortcode: "stethoscope", name: "听诊器", category: "物体", keywords: ["stethoscope"] },
  { emoji: "🚪", shortcode: "door", name: "门", category: "物体", keywords: ["door"] },
  { emoji: "🛗", shortcode: "elevator", name: "电梯", category: "物体", keywords: ["elevator"] },
  { emoji: "🪞", shortcode: "mirror", name: "镜子", category: "物体", keywords: ["mirror"] },
  { emoji: "🪟", shortcode: "window", name: "窗户", category: "物体", keywords: ["window"] },
  { emoji: "🛏️", shortcode: "bed", name: "床", category: "物体", keywords: ["bed"] },
  { emoji: "🛋️", shortcode: "couch_and_lamp", name: "沙发", category: "物体", keywords: ["couch", "lamp"] },
  { emoji: "🪑", shortcode: "chair", name: "椅子", category: "物体", keywords: ["chair"] },
  { emoji: "🚽", shortcode: "toilet", name: "马桶", category: "物体", keywords: ["toilet"] },
  { emoji: "🚿", shortcode: "shower", name: "淋浴", category: "物体", keywords: ["shower"] },
  { emoji: "🛁", shortcode: "bathtub", name: "浴缸", category: "物体", keywords: ["bathtub"] },
  { emoji: "🪒", shortcode: "razor", name: "剃须刀", category: "物体", keywords: ["razor"] },
  { emoji: "🧴", shortcode: "lotion_bottle", name: "乳液瓶", category: "物体", keywords: ["lotion", "bottle"] },
  { emoji: "🧷", shortcode: "safety_pin", name: "安全别针", category: "物体", keywords: ["safety", "pin"] },
  { emoji: "🧹", shortcode: "broom", name: "扫帚", category: "物体", keywords: ["broom"] },
  { emoji: "🧺", shortcode: "basket", name: "篮子", category: "物体", keywords: ["basket"] },
  { emoji: "🧻", shortcode: "roll_of_paper", name: "纸卷", category: "物体", keywords: ["roll", "paper", "toilet paper"] },
  { emoji: "🪣", shortcode: "bucket", name: "水桶", category: "物体", keywords: ["bucket"] },
  { emoji: "🧼", shortcode: "soap", name: "肥皂", category: "物体", keywords: ["soap"] },
  { emoji: "🪥", shortcode: "toothbrush", name: "牙刷", category: "物体", keywords: ["toothbrush"] },
  { emoji: "🧽", shortcode: "sponge", name: "海绵", category: "物体", keywords: ["sponge"] },
  { emoji: "🧯", shortcode: "fire_extinguisher", name: "灭火器", category: "物体", keywords: ["fire", "extinguisher"] },
  { emoji: "🛒", shortcode: "shopping_cart", name: "购物车", category: "物体", keywords: ["shopping", "cart"] },
  { emoji: "🚬", shortcode: "smoking", name: "吸烟", category: "物体", keywords: ["smoking", "cigarette"] },
  { emoji: "⚰️", shortcode: "coffin", name: "棺材", category: "物体", keywords: ["coffin"] },
  { emoji: "🪦", shortcode: "headstone", name: "墓碑", category: "物体", keywords: ["headstone"] },
  { emoji: "🧿", shortcode: "nazar_amulet", name: "护身符", category: "物体", keywords: ["nazar", "amulet"] },
  { emoji: "🪝", shortcode: "hook", name: "钩子", category: "物体", keywords: ["hook"] },
  { emoji: "🪚", shortcode: "carpentry_saw", name: "木锯", category: "物体", keywords: ["carpentry", "saw"] },
  { emoji: "🔫", shortcode: "gun", name: "水枪", category: "物体", keywords: ["gun", "pistol"] },
  { emoji: "🧨", shortcode: "firecracker", name: "鞭炮", category: "物体", keywords: ["firecracker"] },
  { emoji: "🗡️", shortcode: "dagger", name: "匕首", category: "物体", keywords: ["dagger"] },
  { emoji: "⚔️", shortcode: "crossed_swords", name: "交叉剑", category: "物体", keywords: ["crossed", "swords"] },
  { emoji: "🛡️", shortcode: "shield", name: "盾牌", category: "物体", keywords: ["shield"] },

  // ===== 符号 =====
  { emoji: "🏧", shortcode: "atm", name: "ATM", category: "符号", keywords: ["atm", "取款机"] },
  { emoji: "🚮", shortcode: "put_litter_in_its_place", name: "丢垃圾", category: "符号", keywords: ["litter"] },
  { emoji: "🚰", shortcode: "potable_water", name: "饮用水", category: "符号", keywords: ["water", "potable"] },
  { emoji: "♿", shortcode: "wheelchair", name: "无障碍", category: "符号", keywords: ["wheelchair", "accessibility"] },
  { emoji: "🚹", shortcode: "mens", name: "男厕所", category: "符号", keywords: ["men", "restroom"] },
  { emoji: "🚺", shortcode: "womens", name: "女厕所", category: "符号", keywords: ["women", "restroom"] },
  { emoji: "🚻", shortcode: "restroom", name: "厕所", category: "符号", keywords: ["restroom"] },
  { emoji: "🚼", shortcode: "baby_symbol", name: "母婴室", category: "符号", keywords: ["baby"] },
  { emoji: "🚾", shortcode: "wc", name: "卫生间", category: "符号", keywords: ["wc"] },
  { emoji: "🛂", shortcode: "passport_control", name: "护照检查", category: "符号", keywords: ["passport", "control"] },
  { emoji: "🛃", shortcode: "customs", name: "海关", category: "符号", keywords: ["customs"] },
  { emoji: "🛄", shortcode: "baggage_claim", name: "行李提取", category: "符号", keywords: ["baggage", "claim"] },
  { emoji: "🛅", shortcode: "left_luggage", name: "行李寄存", category: "符号", keywords: ["left", "luggage"] },
  { emoji: "⚠️", shortcode: "warning", name: "警告", category: "符号", keywords: ["warning", "注意"] },
  { emoji: "🚸", shortcode: "children_crossing", name: "儿童过街", category: "符号", keywords: ["children", "crossing"] },
  { emoji: "⛔", shortcode: "no_entry", name: "禁止入内", category: "符号", keywords: ["no", "entry"] },
  { emoji: "🚫", shortcode: "no_entry_sign", name: "禁止", category: "符号", keywords: ["no", "entry", "forbidden"] },
  { emoji: "🚳", shortcode: "no_bicycles", name: "禁止骑车", category: "符号", keywords: ["no", "bicycles"] },
  { emoji: "🚭", shortcode: "no_smoking", name: "禁止吸烟", category: "符号", keywords: ["no", "smoking"] },
  { emoji: "🚯", shortcode: "do_not_litter", name: "禁止乱扔", category: "符号", keywords: ["do", "not", "litter"] },
  { emoji: "🚱", shortcode: "non-potable_water", name: "非饮用水", category: "符号", keywords: ["non", "potable"] },
  { emoji: "🚷", shortcode: "no_pedestrians", name: "禁止行人", category: "符号", keywords: ["no", "pedestrians"] },
  { emoji: "📵", shortcode: "no_mobile_phones", name: "禁用手机", category: "符号", keywords: ["no", "mobile", "phones"] },
  { emoji: "🔞", shortcode: "underage", name: "未成年人禁止", category: "符号", keywords: ["underage", "18"] },
  { emoji: "☢️", shortcode: "radioactive", name: "放射性", category: "符号", keywords: ["radioactive"] },
  { emoji: "☣️", shortcode: "biohazard", name: "生物危害", category: "符号", keywords: ["biohazard"] },
  { emoji: "⬆️", shortcode: "arrow_up", name: "上箭头", category: "符号", keywords: ["arrow", "up"] },
  { emoji: "↗️", shortcode: "arrow_upper_right", name: "右上箭头", category: "符号", keywords: ["arrow", "upper", "right"] },
  { emoji: "➡️", shortcode: "arrow_right", name: "右箭头", category: "符号", keywords: ["arrow", "right"] },
  { emoji: "↘️", shortcode: "arrow_lower_right", name: "右下箭头", category: "符号", keywords: ["arrow", "lower", "right"] },
  { emoji: "⬇️", shortcode: "arrow_down", name: "下箭头", category: "符号", keywords: ["arrow", "down"] },
  { emoji: "↙️", shortcode: "arrow_lower_left", name: "左下箭头", category: "符号", keywords: ["arrow", "lower", "left"] },
  { emoji: "⬅️", shortcode: "arrow_left", name: "左箭头", category: "符号", keywords: ["arrow", "left"] },
  { emoji: "↖️", shortcode: "arrow_upper_left", name: "左上箭头", category: "符号", keywords: ["arrow", "upper", "left"] },
  { emoji: "↕️", shortcode: "arrow_up_down", name: "上下箭头", category: "符号", keywords: ["arrow", "up", "down"] },
  { emoji: "↔️", shortcode: "left_right_arrow", name: "左右箭头", category: "符号", keywords: ["left", "right", "arrow"] },
  { emoji: "🔄", shortcode: "arrows_counterclockwise", name: "逆时针", category: "符号", keywords: ["arrows", "counterclockwise"] },
  { emoji: "🔃", shortcode: "arrows_clockwise", name: "顺时针", category: "符号", keywords: ["arrows", "clockwise"] },
  { emoji: "↪️", shortcode: "leftwards_arrow_with_hook", name: "左弯箭头", category: "符号", keywords: ["leftwards", "hook"] },
  { emoji: "↩️", shortcode: "rightwards_arrow_with_hook", name: "右弯箭头", category: "符号", keywords: ["rightwards", "hook"] },
  { emoji: "⤴️", shortcode: "arrow_heading_up", name: "右上弯箭头", category: "符号", keywords: ["arrow", "heading", "up"] },
  { emoji: "⤵️", shortcode: "arrow_heading_down", name: "右下弯箭头", category: "符号", keywords: ["arrow", "heading", "down"] },
  { emoji: "➕", shortcode: "heavy_plus_sign", name: "加号", category: "符号", keywords: ["plus", "add"] },
  { emoji: "➖", shortcode: "heavy_minus_sign", name: "减号", category: "符号", keywords: ["minus", "subtract"] },
  { emoji: "➗", shortcode: "heavy_division_sign", name: "除号", category: "符号", keywords: ["division", "divide"] },
  { emoji: "✖️", shortcode: "heavy_multiplication_x", name: "乘号", category: "符号", keywords: ["multiplication", "multiply", "x"] },
  { emoji: "♾️", shortcode: "infinity", name: "无穷大", category: "符号", keywords: ["infinity"] },
  { emoji: "💲", shortcode: "heavy_dollar_sign", name: "美元符号", category: "符号", keywords: ["dollar", "sign"] },
  { emoji: "💱", shortcode: "currency_exchange", name: "货币兑换", category: "符号", keywords: ["currency", "exchange"] },
  { emoji: "™️", shortcode: "tm", name: "商标", category: "符号", keywords: ["tm", "trademark"] },
  { emoji: "©️", shortcode: "copyright", name: "版权", category: "符号", keywords: ["copyright"] },
  { emoji: "®️", shortcode: "registered", name: "注册商标", category: "符号", keywords: ["registered"] },
  { emoji: "❗", shortcode: "exclamation", name: "感叹号", category: "符号", keywords: ["exclamation", "bang"] },
  { emoji: "❓", shortcode: "question", name: "问号", category: "符号", keywords: ["question"] },
  { emoji: "‼️", shortcode: "bangbang", name: "双感叹号", category: "符号", keywords: ["bangbang"] },
  { emoji: "⁉️", shortcode: "interrobang", name: "感叹问号", category: "符号", keywords: ["interrobang"] },
  { emoji: "✅", shortcode: "white_check_mark", name: "对勾", category: "符号", keywords: ["check", "yes", "done"], popular: true },
  { emoji: "☑️", shortcode: "ballot_box_with_check", name: "勾选框", category: "符号", keywords: ["ballot", "check"] },
  { emoji: "✔️", shortcode: "heavy_check_mark", name: "重对勾", category: "符号", keywords: ["heavy", "check"] },
  { emoji: "❌", shortcode: "x", name: "叉号", category: "符号", keywords: ["x", "cross", "no"], popular: true },
  { emoji: "❎", shortcode: "negative_squared_cross_mark", name: "方框叉", category: "符号", keywords: ["negative", "cross"] },
  { emoji: "➰", shortcode: "curly_loop", name: "卷曲环", category: "符号", keywords: ["curly", "loop"] },
  { emoji: "➿", shortcode: "loop", name: "双环", category: "符号", keywords: ["loop"] },
  { emoji: "〽️", shortcode: "part_alternation_mark", name: "交替符", category: "符号", keywords: ["part", "alternation"] },
  { emoji: "✳️", shortcode: "eight_spoked_asterisk", name: "八角星号", category: "符号", keywords: ["asterisk"] },
  { emoji: "✴️", shortcode: "eight_pointed_black_star", name: "八角星", category: "符号", keywords: ["star"] },
  { emoji: "❇️", shortcode: "sparkle", name: "闪亮符号", category: "符号", keywords: ["sparkle"] },
  { emoji: "🔱", shortcode: "trident", name: "三叉戟", category: "符号", keywords: ["trident"] },
  { emoji: "📛", shortcode: "name_badge", name: "名牌", category: "符号", keywords: ["name", "badge"] },
  { emoji: "🔰", shortcode: "beginner", name: "新手", category: "符号", keywords: ["beginner", "japanese"] },
  { emoji: "⭕", shortcode: "o", name: "圆圈", category: "符号", keywords: ["circle", "o"] },
  { emoji: "🔘", shortcode: "radio_button", name: "单选按钮", category: "符号", keywords: ["radio", "button"] },
  { emoji: "🔴", shortcode: "red_circle", name: "红圈", category: "符号", keywords: ["red", "circle"] },
  { emoji: "🟠", shortcode: "orange_circle", name: "橙圈", category: "符号", keywords: ["orange", "circle"] },
  { emoji: "🟡", shortcode: "yellow_circle", name: "黄圈", category: "符号", keywords: ["yellow", "circle"] },
  { emoji: "🟢", shortcode: "green_circle", name: "绿圈", category: "符号", keywords: ["green", "circle"] },
  { emoji: "🔵", shortcode: "blue_circle", name: "蓝圈", category: "符号", keywords: ["blue", "circle"] },
  { emoji: "🟣", shortcode: "purple_circle", name: "紫圈", category: "符号", keywords: ["purple", "circle"] },
  { emoji: "🟤", shortcode: "brown_circle", name: "棕圈", category: "符号", keywords: ["brown", "circle"] },
  { emoji: "⚫", shortcode: "black_circle", name: "黑圈", category: "符号", keywords: ["black", "circle"] },
  { emoji: "⚪", shortcode: "white_circle", name: "白圈", category: "符号", keywords: ["white", "circle"] },
  { emoji: "🟥", shortcode: "red_square", name: "红方块", category: "符号", keywords: ["red", "square"] },
  { emoji: "🟧", shortcode: "orange_square", name: "橙方块", category: "符号", keywords: ["orange", "square"] },
  { emoji: "🟨", shortcode: "yellow_square", name: "黄方块", category: "符号", keywords: ["yellow", "square"] },
  { emoji: "🟩", shortcode: "green_square", name: "绿方块", category: "符号", keywords: ["green", "square"] },
  { emoji: "🟦", shortcode: "blue_square", name: "蓝方块", category: "符号", keywords: ["blue", "square"] },
  { emoji: "🟪", shortcode: "purple_square", name: "紫方块", category: "符号", keywords: ["purple", "square"] },
  { emoji: "⬛", shortcode: "black_large_square", name: "黑方块", category: "符号", keywords: ["black", "square"] },
  { emoji: "⬜", shortcode: "white_large_square", name: "白方块", category: "符号", keywords: ["white", "square"] },
  { emoji: "🔶", shortcode: "large_orange_diamond", name: "橙菱形", category: "符号", keywords: ["orange", "diamond"] },
  { emoji: "🔷", shortcode: "large_blue_diamond", name: "蓝菱形", category: "符号", keywords: ["blue", "diamond"] },
  { emoji: "🔸", shortcode: "small_orange_diamond", name: "小橙菱形", category: "符号", keywords: ["orange", "diamond"] },
  { emoji: "🔹", shortcode: "small_blue_diamond", name: "小蓝菱形", category: "符号", keywords: ["blue", "diamond"] },
  { emoji: "🔺", shortcode: "red_triangle_up", name: "红三角", category: "符号", keywords: ["red", "triangle"] },
  { emoji: "🔻", shortcode: "red_triangle_down", name: "倒红三角", category: "符号", keywords: ["red", "triangle", "down"] },
  { emoji: "💠", shortcode: "diamond_shape_with_a_dot_inside", name: "菱形点", category: "符号", keywords: ["diamond"] },
  { emoji: "🔲", shortcode: "black_square_button", name: "黑按钮", category: "符号", keywords: ["black", "square", "button"] },
  { emoji: "🔳", shortcode: "white_square_button", name: "白按钮", category: "符号", keywords: ["white", "square", "button"] },
  { emoji: "🔈", shortcode: "speaker", name: "小音量", category: "符号", keywords: ["speaker", "volume"] },
  { emoji: "🔉", shortcode: "sound", name: "中音量", category: "符号", keywords: ["sound", "volume"] },
  { emoji: "🔊", shortcode: "loud_sound", name: "大音量", category: "符号", keywords: ["loud", "sound"] },
  { emoji: "📢", shortcode: "loudspeaker", name: "喇叭", category: "符号", keywords: ["loudspeaker", "announce"] },
  { emoji: "📣", shortcode: "mega", name: "扩音器", category: "符号", keywords: ["mega", "megaphone"] },
  { emoji: "🔔", shortcode: "bell", name: "铃铛", category: "符号", keywords: ["bell"] },
  { emoji: "🔕", shortcode: "no_bell", name: "静音铃铛", category: "符号", keywords: ["no", "bell"] },
  { emoji: "🎵", shortcode: "musical_note", name: "音符", category: "符号", keywords: ["musical", "note"] },
  { emoji: "🎶", shortcode: "notes", name: "多个音符", category: "符号", keywords: ["notes", "music"] },
  { emoji: "🎼", shortcode: "musical_score", name: "乐谱", category: "符号", keywords: ["musical", "score"] },
  { emoji: "🔝", shortcode: "top", name: "顶部", category: "符号", keywords: ["top", "up"] },
  { emoji: "🔚", shortcode: "end", name: "结束", category: "符号", keywords: ["end"] },
  { emoji: "🔙", shortcode: "back", name: "返回", category: "符号", keywords: ["back"] },
  { emoji: "🔛", shortcode: "on", name: "开启", category: "符号", keywords: ["on"] },
  { emoji: "🔜", shortcode: "soon", name: "即将", category: "符号", keywords: ["soon"] },
  { emoji: "🆗", shortcode: "ok", name: "OK 按钮", category: "符号", keywords: ["ok"] },
  { emoji: "🆕", shortcode: "new", name: "新", category: "符号", keywords: ["new"] },
  { emoji: "🆙", shortcode: "up", name: "升级", category: "符号", keywords: ["up", "upgrade"] },
  { emoji: "🆒", shortcode: "cool", name: "酷", category: "符号", keywords: ["cool"] },
  { emoji: "🆓", shortcode: "free", name: "免费", category: "符号", keywords: ["free"] },
  { emoji: "🆖", shortcode: "ng", name: "NG", category: "符号", keywords: ["ng", "no good"] },
  { emoji: "🆘", shortcode: "sos", name: "求救", category: "符号", keywords: ["sos", "help"] },
  { emoji: "🆔", shortcode: "id", name: "ID", category: "符号", keywords: ["id", "identity"] },
  { emoji: "🆚", shortcode: "vs", name: "对战", category: "符号", keywords: ["vs", "versus"] },
  { emoji: "🔟", shortcode: "ten", name: "10", category: "符号", keywords: ["ten", "10"] },
  { emoji: "🔢", shortcode: "input_numbers", name: "数字输入", category: "符号", keywords: ["input", "numbers"] },
  { emoji: "🔣", shortcode: "input_symbols", name: "符号输入", category: "符号", keywords: ["input", "symbols"] },
  { emoji: "🔤", shortcode: "abc", name: "ABC", category: "符号", keywords: ["abc", "letters"] },
  { emoji: "🔡", shortcode: "ab", name: "小写 AB", category: "符号", keywords: ["ab", "lowercase"] },
  { emoji: "🔠", shortcode: "capital_abcd", name: "大写 ABCD", category: "符号", keywords: ["capital", "abcd"] },
  { emoji: "🅰️", shortcode: "a", name: "A 按钮", category: "符号", keywords: ["a", "button"] },
  { emoji: "🅱️", shortcode: "b", name: "B 按钮", category: "符号", keywords: ["b", "button"] },
  { emoji: "🅾️", shortcode: "o2", name: "O 按钮", category: "符号", keywords: ["o", "button"] },
  { emoji: "🅿️", shortcode: "parking", name: "停车", category: "符号", keywords: ["parking", "p"] },
  { emoji: "Ⓜ️", shortcode: "m", name: "M 按钮", category: "符号", keywords: ["m", "button"] },
  { emoji: "🈹", shortcode: "u5272", name: "割", category: "符号", keywords: ["割", "cut"] },
  { emoji: "🈚", shortcode: "u7121", name: "无", category: "符号", keywords: ["无", "none"] },
  { emoji: "🈲", shortcode: "u7981", name: "禁", category: "符号", keywords: ["禁", "forbidden"] },
  { emoji: "🈴", shortcode: "u5408", name: "合", category: "符号", keywords: ["合"] },
  { emoji: "🈵", shortcode: "u6e80", name: "满", category: "符号", keywords: ["满", "full"] },
  { emoji: "🈶", shortcode: "u6709", name: "有", category: "符号", keywords: ["有"] },
  { emoji: "🈳", shortcode: "u7a7a", name: "空", category: "符号", keywords: ["空", "empty"] },
  { emoji: "🈯", shortcode: "u6307", name: "指", category: "符号", keywords: ["指", "point"] },
  { emoji: "🈺", shortcode: "u55b6", name: "营业", category: "符号", keywords: ["营业", "open"] },
  { emoji: "🈷️", shortcode: "u6708", name: "月", category: "符号", keywords: ["月", "month"] },
  { emoji: "🈸", shortcode: "u7533", name: "申", category: "符号", keywords: ["申"] },
  { emoji: "🈂️", shortcode: "sa", name: "服务费", category: "符号", keywords: ["sa", "service"] },
  { emoji: "㊗️", shortcode: "congratulations", name: "祝", category: "符号", keywords: ["祝", "congratulations"] },
  { emoji: "㊙️", shortcode: "secret", name: "秘", category: "符号", keywords: ["秘", "secret"] },
  { emoji: "🉐", shortcode: "ideograph_advantage", name: "得", category: "符号", keywords: ["得", "get"] },
  { emoji: "🉑", shortcode: "accept", name: "可", category: "符号", keywords: ["可", "ok"] },
  { emoji: "🎦", shortcode: "cinema", name: "影院", category: "符号", keywords: ["cinema", "movie"] },
  { emoji: "🈁", shortcode: "koko", name: "这里", category: "符号", keywords: ["koko", "here"] },
  { emoji: "📶", shortcode: "signal_strength", name: "信号", category: "符号", keywords: ["signal", "wifi"] },
  { emoji: "📳", shortcode: "vibration_mode", name: "震动", category: "符号", keywords: ["vibration", "mode"] },
  { emoji: "📴", shortcode: "mobile_phone_off", name: "关机", category: "符号", keywords: ["mobile", "off"] },
  { emoji: "🛑", shortcode: "stop_sign", name: "停止", category: "符号", keywords: ["stop", "sign"] },
  { emoji: "🟰", shortcode: "heavy_equals_sign", name: "等号", category: "符号", keywords: ["equals", "heavy"] },
];

// 空查询时展示的常用表情（popular 标记项）
export const popularEmojis: EmojiItem[] = emojis.filter((item) => item.popular);

const matchEmoji = (item: EmojiItem, query: string): boolean =>
  item.name.includes(query) ||
  item.shortcode.includes(query) ||
  item.keywords.some((keyword) => keyword.toLocaleLowerCase().includes(query));

// 前缀命中的短代码和名称优先，其次才是子串包含，保证输入 "sm" 先出 smile 而不是 lame。
export const filterEmojis = (query: string, limit = 60): EmojiItem[] => {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return popularEmojis.slice(0, limit);

  const prefixMatches: EmojiItem[] = [];
  const substringMatches: EmojiItem[] = [];
  for (const item of emojis) {
    if (
      item.shortcode.toLocaleLowerCase().startsWith(normalized) ||
      item.name.startsWith(normalized)
    ) {
      prefixMatches.push(item);
    } else if (matchEmoji(item, normalized)) {
      substringMatches.push(item);
    }
  }
  return [...prefixMatches, ...substringMatches].slice(0, limit);
};

export const getEmojiByShortcode = (shortcode: string): EmojiItem | undefined =>
  emojis.find((item) => item.shortcode === shortcode);
