// 主进程、preload 和渲染层共用同一份 channel 名称。
export const IPC_CHANNELS = {
  openFile: "open-file",
  getUpdateLogs: "get-update-logs",
  saveFile: "save-file",
  showErrorMessage: "show-error-message",
  windowMinimize: "window-minimize",
  windowMaximize: "window-maximize",
  windowClose: "window-close",
  confirmWindowClose: "confirm-window-close",
  requestWindowClose: "request-window-close",
  showApplicationMenu: "show-application-menu",
  rendererReady: "renderer-ready",
  menuNewFile: "menu-new-file",
  menuOpenFile: "menu-open-file",
  menuSaveFile: "menu-save-file",
  menuSaveAsFile: "menu-save-as-file",
  readDirectory: "read-directory",
  readFile: "read-file",
  getDirectoryName: "get-directory-name",
  selectEditorFile: "select-editor-file",
  importEditorFile: "import-editor-file",
  attachmentCopyProgress: "attachment-copy-progress",
  saveEditorImage: "save-editor-image",
  readEditorImage: "read-editor-image",
  resolveEditorVideo: "resolve-editor-video",
  openEditorFile: "open-editor-file",
  openLocalLink: "open-local-link",
  checkForUpdates: "check-for-updates",
  openExternalLink: "open-external-link",
  downloadUpdate: "download-update",
  updateDownloadProgress: "update-download-progress",
  installUpdate: "install-update",
} as const;
